version: v1

labels:
  - label: "<Enhancement / Feature>"
    matcher:
      body: ".*Features +\".+\".*"

  - label: "Info / User Interface"
    matcher:
      body: ".*Interface +\".+\".*"

  - label: "Mods"
    matcher:
      body: ".*Mods +\".+\".*"

  - label: "Game: Balance"
    matcher:
      body: ".*Balance +\".+\".*"

  - label: "<Bugfix>"
    matcher:
      body: ".*Bugfixes +\".+\".*"

  - label: "<Bugfix>"
    matcher:
      body: ".*((C|c)lose(s|d)?|(F|f)ix(es|ed)?|(R|r)esolve(s|d)?):?.*#([1-9][0-9]{3,8}).*"

  - label: "Code: Performance"
    matcher:
      body: ".*Performance +\".+\".*"

  - label: "Code: Infrastructure / Style / Static Analysis"
    matcher:
      body: ".*Infrastructure +\".+\".*"

  - label: "Code: Build"
    matcher:
      body: ".*Build +\".+\".*"

  - label: "Translation"
    matcher:
      body: ".*I18N +\".+\".*"
