version: '{branch}.{build}'
image: Visual Studio 2019
configuration: Release
environment:
  matrix:
    - project_name: /msvc-full-features/Cataclysm-vcpkg-static.sln
    - project_name: /msvc-object_creator/ObjectCreator-vcpkg-static.sln
platform: x86
shallow_clone: true
clone_folder: C:\Projects\Cataclysm-DDA
cache:
  - c:\tools\vcpkg\installed
  - c:\Users\appveyor\AppData\Local\vcpkg\
install:
    - cmd: cd c:\tools\vcpkg\
    - cmd: git pull
    - cmd: bootstrap-vcpkg.bat -disableMetrics
    - cmd: vcpkg --triplet %PLATFORM%-windows-static install sdl2 sdl2-image sdl2-mixer[dynamic-load,libflac,mpg123,libmodplug,libvorbis] sdl2-ttf gettext --recurse
build:
  project: ${project_name}
  parallel: true
  verbosity: minimal
only_commits:
  files:
    - '.appveyor.yml'
    - 'msvc-*/**'
    - 'src/**'
    - 'tests/**'
    - 'object_creator/**'
branches:
  only:
    - master
    - object_creator
