version: '{branch}.{build}'
os: Windows
clone_folder: C:\Projects\Cataclysm-DDA
shallow_clone: true
matrix:
    fast_finish: false 
pull_requests:
    do_not_increment_build_number: false
image:
    # - Visual Studio 2017
    - Visual Studio 2015
configuration:
    - Release
    # - Debug
platform:
    - x64
    # - x86
environment:
    PROJECT_NAME: msvc-full-features
    SOLUTION_FILENAME: Cataclysm.sln
    TEMP_FOLDER: C:\Temp
    WINDEPEND_URL: http://dev.narc.ro/cataclysm/WinDepend-MSVC.7z
    WINDEPEND_FILENAME: WinDepend-MSVC.7z
    LUA_URL: https://www.dropbox.com/s/49vexob83bi5nrf/lua.zip?dl=1
    LUA_FILENAME: lua.zip
    matrix:
        - TOOLCHAIN: msvc14
          APPVEYOR_SAVE_CACHE_ON_ERROR: true
cache:
    - '%APPVEYOR_BUILD_FOLDER%\WinDepend'                                 # Cache downloaded dependencies
    - '%APPVEYOR_BUILD_FOLDER%\src'                                       # Cache checked-out source files
    - '%APPVEYOR_BUILD_FOLDER%\%PROJECT_NAME%\%PLATFORM%\%CONFIGURATION%' # Cache object files
install:
    # Add WINDEPEND_PATH
    - cmd: set WINDEPEND_PATH=%APPVEYOR_BUILD_FOLDER%\WinDepend
    # Add LUA_PATH
    - cmd: set LUA_PATH=%WINDEPEND_PATH%
    # Add WINDEPEND_PATH to PATH (for LUA binary)
    - cmd: set PATH=%WINDEPEND_PATH%;%PATH%
    # Download non-cached dependencies
    - ps : |
            If( -not( Test-Path -Path "$($env:TEMP_FOLDER)" ) )
            {
                New-Item -ItemType Directory -Force -Path "$($env:TEMP_FOLDER)" | Out-Null;
            }
            If( -not( Test-Path -Path "$($env:WINDEPEND_PATH)" ) )
            {
                New-Item -ItemType Directory -Force -Path "$($env:WINDEPEND_PATH)" | Out-Null;
                [Net.ServicePointManager]::SecurityProtocol = "Ssl3, Tls, Tls11, Tls12"
                    Start-FileDownload "$($env:WINDEPEND_URL)" -FileName "$($env:TEMP_FOLDER)\$($env:WINDEPEND_FILENAME)";
                7z x -y "$($env:TEMP_FOLDER)\$($env:WINDEPEND_FILENAME)" -o"$($env:APPVEYOR_BUILD_FOLDER)"
                [Net.ServicePointManager]::SecurityProtocol = "Ssl3, Tls, Tls11, Tls12"
                    Start-FileDownload "$($env:LUA_URL)" -FileName "$($env:TEMP_FOLDER)\$($env:LUA_FILENAME)"
                7z x -y "$($env:TEMP_FOLDER)\$($env:LUA_FILENAME)" -o"$($env:LUA_PATH)"
            }
    # Report LUA binary version
    - cmd: lua.exe -v
build:
  project: /%PROJECT_NAME%/%SOLUTION_FILENAME%
  parallel: true
  verbosity: detailed
