version: '{branch}.{build}'
image: Previous Visual Studio 2019
configuration: Release
platform: x64
shallow_clone: true
clone_folder: C:\Projects\Cataclysm-DDA
install:
  - cmd: vcpkg --triplet x64-windows-static install sdl2 sdl2-image sdl2-mixer sdl2-ttf gettext
cache: c:\tools\vcpkg\installed\
build:
  project: /msvc-full-features/Cataclysm-vcpkg-static.sln
  parallel: true
  verbosity: minimal
test_script:
  - cmd: Cataclysm-test-vcpkg-static-Release-x64.exe --rng-seed time
