version: '{branch}.{build}'
image: Visual Studio 2019
configuration: Release
platform: x86
shallow_clone: true
clone_folder: C:\Projects\Cataclysm-DDA
cache:
  - c:\tools\vcpkg\installed
  - c:\Users\appveyor\AppData\Local\vcpkg\
install:
    - cmd: cd c:\tools\vcpkg\
    - cmd: git pull
    - cmd: bootstrap-vcpkg.bat -disableMetrics
    - cmd: vcpkg --triplet %PLATFORM%-windows-static install sdl2 sdl2-image sdl2-mixer[libflac,mpg123,libmodplug,libvorbis] sdl2-ttf gettext --recurse
build:
  project: /msvc-full-features/Cataclysm-vcpkg-static.sln
  parallel: true
  verbosity: minimal
only_commits:
  files:
    - '.appveyor.yml'
    - 'msvc-full-features/**'
    - 'src/**'
    - 'tests/**'
branches:
  only:
    - master
    
