version: '{branch}.{build}'
os: Windows
clone_folder: C:\Projects\Cataclysm-DDA
shallow_clone: true
pull_requests:
    do_not_increment_build_number: false
environment:
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          PROJECT: /msvc-full-features/Cataclysm.sln
          COMPILER: msvc2017
          TOOLCHAIN: msvc15
          PLATFORM: x64
          CONFIGURATION: Release
          APPVEYOR_SAVE_CACHE_ON_ERROR: true
matrix:
    fast_finish: false
cache:
  - 'c:\tools\vcpkg\installed'
install:
    # Install dependency packages (WINDEPEND)
    - cmd: set TEMP_FOLDER=C:\Temp
    - cmd: mkdir "%TEMP_FOLDER%"
    - cmd: mkdir "%APPVEYOR_BUILD_FOLDER%\WinDepend"
    - ps : |
         [Net.ServicePointManager]::SecurityProtocol = 'Ssl3, Tls, Tls11, Tls12'
         Start-FileDownload "http://dev.narc.ro/cataclysm/WinDepend-MSVC.7z" -FileName "$($env:TEMP_FOLDER)\WinDepend-MSVC.7z"
    - cmd: 7z x -y "%TEMP_FOLDER%\WinDepend-MSVC.7z" -o"%APPVEYOR_BUILD_FOLDER%"
    # Install dependency packages (vcpkg)
    - cmd: vcpkg --triplet %PLATFORM%-windows-static install sdl2 sdl2-image sdl2-mixer sdl2-ttf gettext lua
    # Add LUA binary folder to PATH
    - cmd: set PATH=c:\tools\vcpkg\installed\%PLATFORM%-windows-static\tools\lua;%PATH%
    # Report LUA binary version
    - cmd: lua.exe -v
build:
  parallel: true
  project: /msvc-full-features/Cataclysm.sln
  verbosity: detailed
