version: '{branch}.{build}'
image: Visual Studio 2019
configuration: Release
platform: x86
shallow_clone: true
clone_folder: C:\Projects\Cataclysm-DDA
cache:
  - c:\tools\vcpkg\installed
  - c:\Users\appveyor\AppData\Local\vcpkg\
build:
  project: /msvc-full-features/Cataclysm-vcpkg-static.sln
  parallel: true
  verbosity: minimal
test_script:
  - cmd: Cataclysm-test-vcpkg-static-Release-Win32.exe --rng-seed time --min-duration 0.2
skip_commits:
  files:
    - 'doc/**'
    - 'lgtm/**'
    - 'tools/**'
    - '.github/**'
