version: '{branch}.{build}'
image: Visual Studio 2019
configuration: Release
platform: x64
environment:
 APPVEYOR_SAVE_CACHE_ON_ERROR: true
shallow_clone: true
clone_folder: C:\Projects\Cataclysm-DDA
cache:
  - c:\tools\vcpkg\installed\
  - c:\Users\appveyor\AppData\Local\vcpkg\
install:
 - cmd: vcpkg install yasm-tool:x86-windows
 - cmd: vcpkg --triplet x64-windows-static install sdl2 sdl2-image sdl2-mixer[dynamic-load,libflac,mpg123,libmodplug,libvorbis] sdl2-ttf gettext
build:
  project: /msvc-full-features/Cataclysm-vcpkg-static.sln
  parallel: true
  verbosity: minimal
test_script:
  - cmd: Cataclysm-test-vcpkg-static-Release-x64.exe --rng-seed time --min-duration 0.2
