#ifndef _ACTION_H_
#define _ACTION_H_

const std::string action_msg[]={
    "null",
    // Movement
    "pause",
    "move_n",
    "move_ne",
    "move_e",
    "move_se",
    "move_s",
    "move_sw",
    "move_w",
    "move_nw",
    "move_down",
    "move_up",
    // Shift view
    "center",
    "shift_n",
    "shift_ne",
    "shift_e",
    "shift_se",
    "shift_s",
    "shift_sw",
    "shift_w",
    "shift_nw",
    // Environment Interaction
    "open",
    "close",
    "smash",
    "examine",
    "pickup",
    "butcher",
    "chat",
    "look",
    "peek",
    "listitems",
    // Inventory Interaction (including quasi-inventories like bionics)
    "inventory",
    "compare",
    "organize",
    "apply",
    "apply_wielded",
    "wear",
    "take_off",
    "eat",
    "read",
    "wield",
    "pick_style",
    "reload",
    "unload",
    "throw",
    "fire",
    "fire_burst",
    "select_fire_mode",
    "drop",
    "drop_adj",
    "bionics",
    // Long-term / special actions
    "wait",
    "craft",
    "construct",
    "disassemble",
    "sleep",
    "safemode",
    "autosafe",
    "ignore_enemy",
    "save",
    "quit",
    // Info Screens
    "player_data",
    "map",
    "missions",
    "factions",
    "morale",
    "messages",
    "help",
    // Debug Functions
    "debug",
    "debug_scent",
    "debug_mode",
};
enum action_id {
ACTION_NULL = 0,
// Movement
ACTION_PAUSE,
ACTION_MOVE_N,
ACTION_MOVE_NE,
ACTION_MOVE_E,
ACTION_MOVE_SE,
ACTION_MOVE_S,
ACTION_MOVE_SW,
ACTION_MOVE_W,
ACTION_MOVE_NW,
ACTION_MOVE_DOWN,
ACTION_MOVE_UP,
// Shift view
ACTION_CENTER,
ACTION_SHIFT_N,
ACTION_SHIFT_NE,
ACTION_SHIFT_E,
ACTION_SHIFT_SE,
ACTION_SHIFT_S,
ACTION_SHIFT_SW,
ACTION_SHIFT_W,
ACTION_SHIFT_NW,
// Environment Interaction
ACTION_OPEN,
ACTION_CLOSE,
ACTION_SMASH,
ACTION_EXAMINE,
ACTION_PICKUP,
ACTION_BUTCHER,
ACTION_CHAT,
ACTION_LOOK,
ACTION_PEEK,
ACTION_LIST_ITEMS,
// Inventory Interaction (including quasi-inventories like bionics)
ACTION_INVENTORY,
ACTION_COMPARE,
ACTION_ORGANIZE,
ACTION_USE,
ACTION_USE_WIELDED,
ACTION_WEAR,
ACTION_TAKE_OFF,
ACTION_EAT,
ACTION_READ,
ACTION_WIELD,
ACTION_PICK_STYLE,
ACTION_RELOAD,
ACTION_UNLOAD,
ACTION_THROW,
ACTION_FIRE,
ACTION_FIRE_BURST,
ACTION_SELECT_FIRE_MODE,
ACTION_DROP,
ACTION_DIR_DROP,
ACTION_BIONICS,
// Long-term / special actions
ACTION_WAIT,
ACTION_CRAFT,
ACTION_CONSTRUCT,
ACTION_DISASSEMBLE,
ACTION_SLEEP,
ACTION_TOGGLE_SAFEMODE,
ACTION_TOGGLE_AUTOSAFE,
ACTION_IGNORE_ENEMY,
ACTION_SAVE,
ACTION_QUIT,
// Info Screens
ACTION_PL_INFO,
ACTION_MAP,
ACTION_MISSIONS,
ACTION_FACTIONS,
ACTION_MORALE,
ACTION_MESSAGES,
ACTION_HELP,
// Debug Functions
ACTION_DEBUG,
ACTION_DISPLAY_SCENT,
ACTION_TOGGLE_DEBUGMON,
NUM_ACTIONS
};

action_id look_up_action(std::string ident);
std::string action_ident(action_id);
std::string action_name(action_id);

#endif
