#!/bin/sh
DIR=$(dirname "$(readlink -f "$0")")
BIN=$(basename "$0")

cd "$DIR" || exit $?

# If name does not match a binary or is this same script, find the right one
if [ ! -f "$BIN" ] || [ "$BIN" == "$(basename "$(readlink -f "$0")")" ]
then
    BIN=
    for bin in cataclysm-tiles cataclysm
    do
	[ -f "$bin" ] && BIN="$bin" && break
    done
fi

if [ "$BIN" ]
then
    exec "./$BIN"
else
    echo "Couldn't find cataclysm game binary in $DIR/"
    exit 1
fi
