-- Defines which attributes are exported by our C++ classes.

classes = {
    Character = {
        parent = "Creature",
        attributes = {
            male = { type = "bool", writable = true },
            name = { type = "string", writable = true },
            nv_cached = { type = "bool", writable = true },
        },
        functions = {
            add_traits = { rval = nil, args = { } },
            can_pickVolume = { rval = "bool", args = { "int", "bool" } },
            can_pickWeight = { rval = "bool", args = { "int", "bool" } },
            die = { rval = nil, args = { "Creature" } },
            empty_skills = { rval = nil, args = { } },
            empty_traits = { rval = nil, args = { } },
            get_turn_died = { rval = "int", args = { } },
            has_active_bionic = { rval = "bool", args = { "string" } },
            has_active_mutation = { rval = "bool", args = { "string" } },
            has_base_trait = { rval = "bool", args = { "string" } },
            has_bionic = { rval = "bool", args = { "string" } },
            has_nv = { rval = "bool", args = { } },
            has_trait = { rval = "bool", args = { "string" } },
            i_add_or_drop = { rval = "bool", args = { "item", "int" } },
            i_rem_keep_contents = { rval = nil, args = { "int" } },
            is_warm = { rval = "bool", args = { } },
            is_worn = { rval = "bool", args = { "item" } },
            move_effects = { rval = "bool", args = { } },
            mutation_effect = { rval = nil, args = { "string" } },
            mutation_loss_effect = { rval = nil, args = { "string" } },
            normalize = { rval = nil, args = { } },
            pick_name = { rval = nil, args = { } },
            random_bad_trait = { rval = "string", args = { } },
            random_good_trait = { rval = "string", args = { } },
            recalc_hp = { rval = nil, args = { } },
            recalc_sight_limits = { rval = nil, args = { } },
            remove_mission_items = { rval = nil, args = { "int" } },
            reset_stats = { rval = nil, args = { } },
            set_turn_died = { rval = nil, args = { "int" } },
            symbol = { rval = "string", args = { } },
            toggle_mutation = { rval = nil, args = { "string" } },
            toggle_trait = { rval = nil, args = { "string" } },
            trait_by_invlet = { rval = "string", args = { "int" } },
            volume_capacity = { rval = "int", args = { } },
            volume_carried = { rval = "int", args = { } },
            weight_capacity = { rval = "int", args = { } },
            weight_carried = { rval = "int", args = { } },
            worn_with_flag = { rval = "bool", args = { "string" } },
        }
    },
    item_stack_iterator = {
        by_value = true,
        has_equal = true,
        attributes = {
        },
        functions = {
            elem = { rval = "item", cpp_name = "operator*"; args = { } },
            inc = { rval = nil, cpp_name = "operator++", args = { } },
        }
    },
    map_stack = {
        by_value = true,
        attributes = {
        },
        functions = {
            cppbegin = { rval = "item_stack_iterator", cpp_name = "begin", args = { } },
            cppend = { rval = "item_stack_iterator", cpp_name = "end", args = {} },
            empty = { rval = "bool", args = { } },
            erase = { rval = "item_stack_iterator", args = { "item_stack_iterator" } },
            push_back = { rval = nil, args = { "item" } },
            size = { rval = "int", args = { } },
        }
    },
    player = {
        parent = "Character",
        attributes = {
            blocks_left = { type = "int", writable = true },
            cash = { type = "int", writable = true },
            controlling_vehicle = { type = "bool", writable = true },
            dodges_left = { type = "int", writable = true },
            driving_recoil = { type = "int", writable = true },
            fatigue = { type = "int", writable = true },
            focus_pool = { type = "int", writable = true },
            grab_point = { type = "tripoint", writable = true },
            hunger = { type = "int", writable = true },
            in_vehicle = { type = "bool", writable = true },
            keep_hands_free = { type = "bool", writable = true },
            last_batch = { type = "int", writable = true },
            last_climate_control_ret = { type = "bool", writable = true },
            lastrecipe = { type = "string", writable = true },
            max_power_level = { type = "int", writable = true },
            move_mode = { type = "string", writable = true },
            movecounter = { type = "int", writable = true },
            next_climate_control_check = { type = "int", writable = true },
            oxygen = { type = "int", writable = true },
            pda_cached = { type = "bool", writable = true },
            pkill = { type = "int", writable = true },
            power_level = { type = "int", writable = true },
            radiation = { type = "int", writable = true },
            reactor_plut = { type = "int", writable = true },
            recoil = { type = "int", writable = true },
            scent = { type = "int", writable = true },
            slow_rad = { type = "int", writable = true },
            stamina = { type = "int", writable = true },
            start_location = { type = "string", writable = true },
            stim = { type = "int", writable = true },
            stomach_food = { type = "int", writable = true },
            stomach_water = { type = "int", writable = true },
            tank_plut = { type = "int", writable = true },
            thirst = { type = "int", writable = true },
            view_offset = { type = "tripoint", writable = true },
            volume = { type = "int", writable = true },
        },
        functions = {
            action_taken = { rval = nil, args = { } },
            activate_bionic = { rval = "bool", args = { "int", "bool" } },
            active_light = { rval = "float", args = { } },
            add_ammo_to_worn_quiver = { rval = "int", args = { "item" } },
            add_bionic = { rval = nil, args = { "string" } },
            adjacent_tile = { rval = "tripoint", args = { } },
            adjust_for_focus = { rval = "int", args = { "int" } },
            aim_per_time = { rval = "int", args = { "item" } },
            apply_persistent_morale = { rval = nil, args = { } },
            base_damage = { rval = "int", args = { "bool", "int" } },
            base_to_hit = { rval = "int", args = { "bool", "int" } },
            basic_symbol_color = { rval = "int", args = { } },
            blossoms = { rval = nil, args = { } },
            bodytemp_color = { rval = "int", args = { "int" } },
            boost_skill_level = { rval = nil, args = { "string", "int" } },
            burn_move_stamina = { rval = nil, args = { "int" } },
            butcher_factor = { rval = "int", args = { } },
            calc_focus_equilibrium = { rval = "int", args = { } },
            can_arm_block = { rval = "bool", args = { } },
            can_hear = { rval = "bool", args = { "tripoint", "int" } },
            can_leg_block = { rval = "bool", args = { } },
            can_limb_block = { rval = "bool", args = { } },
            can_melee = { rval = "bool", args = { } },
            can_pickup = { rval = "bool", args = { "bool" } },
            can_sleep = { rval = "bool", args = { } },
            can_weapon_block = { rval = "bool", args = { } },
            cancel_activity = { rval = nil, args = { } },
            charge_power = { rval = nil, args = { "int" } },
            clairvoyance = { rval = "int", args = { } },
            clear_destination = { rval = nil, args = { } },
            complete_craft = { rval = nil, args = { } },
            complete_disassemble = { rval = nil, args = { } },
            consume = { rval = "bool", args = { "int" } },
            consume_charges = { rval = "bool", args = { "item", "int" } },
            consume_item = { rval = "bool", args = { "item" } },
            convert_weight = { rval = "float", args = { "int" } },
            copy_skill_levels = { rval = nil, args = { "player" } },
            cough = { rval = nil, args = { "bool", "int" } },
            craft = { rval = nil, args = { } },
            crafting_allowed = { rval = "bool", args = { } },
            crafting_can_see = { rval = "bool", args = { } },
            crossed_threshold = { rval = "bool", args = { } },
            deactivate_bionic = { rval = "bool", args = { "int", "bool" } },
            digging = { rval = "bool", args = { } },
            disassemble = { rval = nil, args = { "int" } },
            disp_info = { rval = nil, args = { } },
            disp_morale = { rval = nil, args = { } },
            disp_name = { rval = "string", args = { "bool" } },
            do_read = { rval = nil, args = { "item" } },
            dodge_hit = { rval = nil, args = { "Creature", "int" } },
            dodge_roll = { rval = "int", args = { } },
            drench = { rval = nil, args = { "int", "int" } },
            drench_mut_calc = { rval = nil, args = { } },
            drink_from_hands = { rval = "int", args = { "item" } },
            dump_memorial = { rval = "string", args = { } },
            environmental_revert_effect = { rval = nil, args = { } },
            fall_asleep = { rval = nil, args = { "int" } },
            fine_detail_vision_mod = { rval = "float", args = { } },
            footwear_factor = { rval = "float", args = { } },
            getID = { rval = "int", args = { } },
            get_active_mission_target = { rval = "tripoint", args = { } },
            get_category_dream = { rval = "string", args = { "string", "int" } },
            get_dodge = { rval = "int", args = { } },
            get_dodge_base = { rval = "int", args = { } },
            get_highest_category = { rval = "string", args = { } },
            get_hit_base = { rval = "int", args = { } },
            get_item_position = { rval = "int", args = { "item" } },
            get_melee = { rval = "int", args = { } },
            get_sick = { rval = nil, args = { } },
            get_stamina_max = { rval = "int", args = { } },
            get_weapon_dispersion = { rval = "float", args = { "item", "bool" } },
            global_omt_location = { rval = "tripoint", args = { } },
            global_sm_location = { rval = "tripoint", args = { } },
            global_square_location = { rval = "tripoint", args = { } },
            handle_melee_wear = { rval = "bool", args = { } },
            has_active_optcloak = { rval = "bool", args = { } },
            has_alarm_clock = { rval = "bool", args = { } },
            has_child_flag = { rval = "bool", args = { "string" } },
            has_conflicting_trait = { rval = "bool", args = { "string" } },
            has_container_for = { rval = "bool", args = { "item" } },
            has_destination = { rval = "bool", args = { } },
            has_grab_break_tec = { rval = "bool", args = { } },
            has_higher_trait = { rval = "bool", args = { "string" } },
            has_identified = { rval = "bool", args = { "string" } },
            has_item = { rval = "bool", args = { "int" } },
            has_item = { rval = "bool", args = { "item" } },
            has_item_with_flag = { rval = "bool", args = { "string" } },
            has_items_with_quality = { rval = "bool", args = { "string", "int", "int" } },
            has_lower_trait = { rval = "bool", args = { "string" } },
            has_miss_recovery_tec = { rval = "bool", args = { } },
            has_mission_item = { rval = "bool", args = { "int" } },
            has_opposite_trait = { rval = "bool", args = { "string" } },
            has_pda = { rval = "bool", args = { } },
            has_two_arms = { rval = "bool", args = { } },
            has_watch = { rval = "bool", args = { } },
            has_weapon = { rval = "bool", args = { } },
            healall = { rval = nil, args = { "int" } },
            hearing_ability = { rval = "float", args = { } },
            hit_roll = { rval = "int", args = { } },
            hitall = { rval = "int", args = { "int", "int", "Creature" } },
            hp_percentage = { rval = "int", args = { } },
            hurtall = { rval = nil, args = { "int", "Creature" } },
            i_at = { rval = "item", args = { "int" } },
            in_climate_control = { rval = "bool", args = { } },
            install_bionics = { rval = "bool", args = { "itype" } },
            intimidation = { rval = "int", args = { } },
            invalidate_crafting_inventory = { rval = nil, args = { } },
            invlet_to_position = { rval = "int", args = { "int" } },
            invoke_item = { rval = "bool", args = { "item" } },
            invoke_item = { rval = "bool", args = { "item", "string" } },
            is_armed = { rval = "bool", args = { } },
            is_dead_state = { rval = "bool", args = { } },
            is_deaf = { rval = "bool", args = { } },
            is_elec_immune = { rval = "bool", args = { } },
            is_hallucination = { rval = "bool", args = { } },
            is_invisible = { rval = "bool", args = { } },
            is_npc = { rval = "bool", args = { } },
            is_on_ground = { rval = "bool", args = { } },
            is_player = { rval = "bool", args = { } },
            is_quiet = { rval = "bool", args = { } },
            is_snuggling = { rval = "string", args = { } },
            is_throw_immune = { rval = "bool", args = { } },
            is_underwater = { rval = "bool", args = { } },
            is_wearing_shoes = { rval = "bool", args = { "string" } },
            knock_back_from = { rval = nil, args = { "tripoint" } },
            knows_trap = { rval = "bool", args = { "tripoint" } },
            leak_level = { rval = "int", args = { "string" } },
            load_info = { rval = nil, args = { "string" } },
            load_zones = { rval = nil, args = { } },
            logistic = { rval = "float", args = { "float" } },
            logistic_range = { rval = "float", args = { "int", "int", "int" } },
            long_craft = { rval = nil, args = { } },
            ma_onattack_effects = { rval = nil, args = { } },
            ma_onblock_effects = { rval = nil, args = { } },
            ma_ondodge_effects = { rval = nil, args = { } },
            ma_ongethit_effects = { rval = nil, args = { } },
            ma_onhit_effects = { rval = nil, args = { } },
            ma_onmove_effects = { rval = nil, args = { } },
            ma_static_effects = { rval = nil, args = { } },
            mabuff_arm_bash_bonus = { rval = "int", args = { } },
            mabuff_arm_cut_bonus = { rval = "int", args = { } },
            mabuff_bash_bonus = { rval = "int", args = { } },
            mabuff_bash_mult = { rval = "float", args = { } },
            mabuff_block_bonus = { rval = "int", args = { } },
            mabuff_cut_bonus = { rval = "int", args = { } },
            mabuff_cut_mult = { rval = "float", args = { } },
            mabuff_dodge_bonus = { rval = "int", args = { } },
            mabuff_speed_bonus = { rval = "int", args = { } },
            mabuff_tohit_bonus = { rval = "int", args = { } },
            make_all_craft = { rval = nil, args = { "string", "int" } },
            make_craft = { rval = nil, args = { "string", "int" } },
            making_would_work = { rval = "bool", args = { "string", "int" } },
            mend = { rval = nil, args = { } },
            mod_pain = { rval = nil, args = { "int" } },
            mod_stat = { rval = nil, args = { "string", "int" } },
            morale_level = { rval = "int", args = { } },
            mutate = { rval = nil, args = { } },
            mutate_category = { rval = nil, args = { "string" } },
            mutate_towards = { rval = nil, args = { "string" } },
            mutation_ok = { rval = "bool", args = { "string", "bool", "bool" } },
            normalize = { rval = nil, args = { } },
            num_bionics = { rval = "int", args = { } },
            on_dodge = { rval = nil, args = { "Creature", "int" } },
            overmap_los = { rval = "bool", args = { "tripoint", "int" } },
            overmap_sight_range = { rval = "int", args = { "int" } },
            pause = { rval = nil, args = { } },
            perform_special_attacks = { rval = nil, args = { "Creature" } },
            pick_style = { rval = nil, args = { } },
            pick_usb = { rval = "item", args = { } },
            place_corpse = { rval = nil, args = { } },
            pos = { rval = "tripoint", args = { } },
            posx = { rval = "int", args = { } },
            posy = { rval = "int", args = { } },
            posz = { rval = "int", args = { } },
            power_bionics = { rval = nil, args = { } },
            power_mutations = { rval = nil, args = { } },
            power_rating = { rval = "float", args = { } },
            practice = { rval = nil, args = { "string", "int", "int" } },
            process_active_items = { rval = nil, args = { } },
            process_bionic = { rval = nil, args = { "int" } },
            process_effects = { rval = nil, args = { } },
            process_turn = { rval = nil, args = { } },
            purifiable = { rval = "bool", args = { "string" } },
            ranged_dex_mod = { rval = "int", args = { } },
            ranged_per_mod = { rval = "int", args = { } },
            read = { rval = nil, args = { "int" } },
            read_speed = { rval = "int", args = { "bool" } },
            recalc_speed_bonus = { rval = nil, args = { } },
            recraft = { rval = nil, args = { } },
            regen = { rval = nil, args = { } },
            remove_bionic = { rval = nil, args = { "string" } },
            remove_child_flag = { rval = nil, args = { "string" } },
            remove_gunmod = { rval = nil, args = { "item", "int" } },
            remove_mutation = { rval = nil, args = { "string" } },
            remove_random_bionic = { rval = "bool", args = { } },
            reset_stats = { rval = nil, args = { } },
            rooted = { rval = nil, args = { } },
            rooted_message = { rval = nil, args = { } },
            run_cost = { rval = "int", args = { "int", "bool" } },
            rust_rate = { rval = "int", args = { "bool" } },
            save_info = { rval = "string", args = { } },
            save_zones = { rval = "bool", args = { } },
            scored_crit = { rval = "bool", args = { "int" } },
            search_surroundings = { rval = nil, args = { } },
            sees_with_infrared = { rval = "bool", args = { "Creature" } },
            setID = { rval = nil, args = { "int" } },
            set_cat_level_rec = { rval = nil, args = { "string" } },
            set_highest_cat_level = { rval = nil, args = { } },
            set_skill_level = { rval = nil, args = { "string", "int" } },
            setpos = { rval = nil, args = { "tripoint" } },
            setx = { rval = nil, args = { "int" } },
            sety = { rval = nil, args = { "int" } },
            setz = { rval = nil, args = { "int" } },
            shift_destination = { rval = nil, args = { "int", "int" } },
            sight_impaired = { rval = "bool", args = { } },
            sight_range = { rval = "int", args = { "int" } },
            skill_dispersion = { rval = "int", args = { "item", "bool" } },
            skin_name = { rval = "string", args = { } },
            sleep_spot = { rval = "int", args = { "tripoint" } },
            sort_armor = { rval = nil, args = { } },
            spores = { rval = nil, args = { } },
            store = { rval = nil, args = { "item", "item", "string", "int" } },
            studied_all_recipes = { rval = "bool", args = { "itype" } },
            suffer = { rval = nil, args = { } },
            swim_speed = { rval = "int", args = { } },
            talk_skill = { rval = "int", args = { } },
            throw_dex_mod = { rval = "int", args = { "bool" } },
            throw_range = { rval = "int", args = { "int" } },
            toggle_move_mode = { rval = nil, args = { } },
            try_to_sleep = { rval = nil, args = { } },
            unarmed_attack = { rval = "bool", args = { } },
            uncanny_dodge = { rval = "bool", args = { } },
            unimpaired_range = { rval = "int", args = { } },
            uninstall_bionic = { rval = "bool", args = { "string" } },
            update_body_wetness = { rval = nil, args = { } },
            update_bodytemp = { rval = nil, args = { } },
            update_health = { rval = nil, args = { "int" } },
            update_mental_focus = { rval = nil, args = { } },
            update_morale = { rval = nil, args = { } },
            update_needs = { rval = nil, args = { } },
            update_stamina = { rval = nil, args = { } },
            use = { rval = nil, args = { "int" } },
            use_wielded = { rval = nil, args = { } },
            visibility = { rval = "int", args = { "bool", "int" } },
            vomit = { rval = nil, args = { } },
            vomit_mod = { rval = "float", args = { } },
            wake_up = { rval = nil, args = { } },
            weapname = { rval = "string", args = { "bool" } },
            wear = { rval = "bool", args = { "int", "bool" } },
            wear_item = { rval = "bool", args = { "item", "bool" } },
            wield = { rval = "bool", args = { "item", "bool" } },
            wield_contents = { rval = nil, args = { "item", "bool", "string", "int" } },
        }
    },
    item = {
        attributes = {
            active = { type = "bool", writable = true },
            bday = { type = "int", writable = true },
            burnt = { type = "int", writable = true },
            charges = { type = "int", writable = true },
            damage = { type = "int", writable = true },
            fridge = { type = "int", writable = true },
            invlet = { type = "int", writable = true },
            item_counter = { type = "int", writable = true },
            mission_id = { type = "int", writable = true },
            player_id = { type = "int", writable = true },
            type = { type = "itype", writable = true },
        },
        functions = {
            acid_resist = { rval = "int", args = { } },
            activate_charger_gun = { rval = "bool", args = { "player" } },
            active_gunmod = { rval = "item", args = { } },
            active_gunmod = { rval = "item", args = { } },
            add_rain_to_container = { rval = nil, args = { "bool", "int" } },
            aim_speed = { rval = "int", args = { "int" } },
            already_used_by_player = { rval = "bool", args = { "player" } },
            attack_time = { rval = "int", args = { } },
            bash_resist = { rval = "int", args = { } },
            brewing_time = { rval = "int", args = { } },
            burn = { rval = "bool", args = { "int" } },
            burst_size = { rval = "int", args = { } },
            butcher_factor = { rval = "int", args = { } },
            calc_rot = { rval = nil, args = { "tripoint" } },
            can_revive = { rval = "bool", args = { } },
            clear = { rval = nil, args = { } },
            clip_size = { rval = "int", args = { } },
            color = { rval = "int", args = { "player" } },
            color = { rval = "int", args = { } },
            color_in_inventory = { rval = "int", args = { } },
            components_to_string = { rval = "string", args = { } },
            conductive = { rval = "bool", args = { } },
            contains_with_flag = { rval = "bool", args = { "string" } },
            count_by_charges = { rval = "bool", args = { } },
            craft_has_charges = { rval = "bool", args = { } },
            cut_resist = { rval = "int", args = { } },
            damage_bash = { rval = "int", args = { } },
            damage_cut = { rval = "int", args = { } },
            deactivate_charger_gun = { rval = "bool", args = { } },
            destroyed_at_zero_charges = { rval = "bool", args = { } },
            detonate = { rval = nil, args = { "tripoint" } },
            display_name = { rval = "string", args = { "int" } },
            erase_var = { rval = nil, args = { "string" } },
            flammable = { rval = "bool", args = { } },
            get_chapters = { rval = "int", args = { } },
            get_coverage = { rval = "int", args = { } },
            get_curammo = { rval = "itype", args = { } },
            get_encumber = { rval = "int", args = { } },
            get_env_resist = { rval = "int", args = { } },
            get_free_mod_locations = { rval = "int", args = { "string" } },
            get_gun_mode = { rval = "string", args = { } },
            get_mtype = { rval = "mtype", args = { } },
            get_plant_epoch = { rval = "int", args = { } },
            get_plant_name = { rval = "string", args = { } },
            get_relative_rot = { rval = "float", args = { } },
            get_remaining_capacity_for_liquid = { rval = "int", args = { "item" } },
            get_remaining_chapters = { rval = "int", args = { "player" } },
            get_rot = { rval = "int", args = { } },
            get_storage = { rval = "int", args = { } },
            get_thickness = { rval = "int", args = { } },
            get_usable_item = { rval = "item", args = { "string" } },
            get_var = { rval = "int", args = { "string", "int" } },
            get_var = { rval = "int", args = { "string", "int" } },
            get_var = { rval = "string", args = { "string" } },
            get_var = { rval = "string", args = { "string", "string" } },
            get_warmth = { rval = "int", args = { } },
            getlight_emit = { rval = "int", args = { } },
            getlight_emit_active = { rval = "int", args = { } },
            goes_bad = { rval = "bool", args = { } },
            gun_damage = { rval = "int", args = { "bool" } },
            gun_dispersion = { rval = "int", args = { "bool" } },
            gun_pierce = { rval = "int", args = { "bool" } },
            gun_range = { rval = "int", args = { "bool" } },
            gun_range = { rval = "int", args = { "player" } },
            gun_recoil = { rval = "int", args = { "bool" } },
            gun_skill = { rval = "string", args = { } },
            has_curammo = { rval = "bool", args = { } },
            has_flag = { rval = "bool", args = { "string" } },
            has_quality = { rval = "bool", args = { "string" } },
            has_quality = { rval = "bool", args = { "string", "int" } },
            has_rotten_away = { rval = "bool", args = { } },
            has_var = { rval = "bool", args = { "string" } },
            info = { rval = "string", args = { "bool" } },
            init = { rval = nil, args = { } },
            invlet_is_okay = { rval = "bool", args = { } },
            is_ammo = { rval = "bool", args = { } },
            is_ammo_container = { rval = "bool", args = { } },
            is_armor = { rval = "bool", args = { } },
            is_artifact = { rval = "bool", args = { } },
            is_auxiliary_gunmod = { rval = "bool", args = { } },
            is_bashing_weapon = { rval = "bool", args = { } },
            is_bionic = { rval = "bool", args = { } },
            is_book = { rval = "bool", args = { } },
            is_charger_gun = { rval = "bool", args = { } },
            is_container = { rval = "bool", args = { } },
            is_container_empty = { rval = "bool", args = { } },
            is_container_full = { rval = "bool", args = { } },
            is_corpse = { rval = "bool", args = { } },
            is_cutting_weapon = { rval = "bool", args = { } },
            is_disassemblable = { rval = "bool", args = { } },
            is_drink = { rval = "bool", args = { } },
            is_emissive = { rval = "bool", args = { } },
            is_food = { rval = "bool", args = { "player" } },
            is_food = { rval = "bool", args = { } },
            is_food_container = { rval = "bool", args = { "player" } },
            is_food_container = { rval = "bool", args = { } },
            is_going_bad = { rval = "bool", args = { } },
            is_gun = { rval = "bool", args = { } },
            is_gunmod = { rval = "bool", args = { } },
            is_in_auxiliary_mode = { rval = "bool", args = { } },
            is_null = { rval = "bool", args = { } },
            is_power_armor = { rval = "bool", args = { } },
            is_salvageable = { rval = "bool", args = { } },
            is_seed = { rval = "bool", args = { } },
            is_silent = { rval = "bool", args = { } },
            is_software = { rval = "bool", args = { } },
            is_tool = { rval = "bool", args = { } },
            is_tool_reversible = { rval = "bool", args = { } },
            is_two_handed = { rval = "bool", args = { "player" } },
            is_var_veh_part = { rval = "bool", args = { } },
            is_watertight_container = { rval = "bool", args = { } },
            is_weap = { rval = "bool", args = { } },
            liquid_charges = { rval = "int", args = { "int" } },
            liquid_units = { rval = "int", args = { "int" } },
            load_info = { rval = nil, args = { "string" } },
            made_of = { rval = "bool", args = { "string" } },
            make = { rval = nil, args = { "string" } },
            make_corpse = { rval = nil, args = { "mtype", "int" } },
            make_corpse = { rval = nil, args = { "mtype", "int", "string" } },
            make_corpse = { rval = nil, args = { "string", "int" } },
            make_corpse = { rval = nil, args = { } },
            mark_as_used_by_player = { rval = nil, args = { "player" } },
            mark_chapter_as_read = { rval = nil, args = { "player" } },
            max_charges_from_flag = { rval = "int", args = { "string" } },
            melee_value = { rval = "int", args = { "player" } },
            merge_charges = { rval = "bool", args = { "item" } },
            needs_processing = { rval = "bool", args = { } },
            next_mode = { rval = nil, args = { } },
            noise = { rval = "int", args = { } },
            num_charges = { rval = "int", args = { } },
            on_wear = { rval = nil, args = { "player" } },
            on_wield = { rval = nil, args = { "player" } },
            pick_reload_ammo = { rval = "int", args = { "player", "bool" } },
            precise_unit_volume = { rval = "int", args = { } },
            price = { rval = "int", args = { } },
            process = { rval = "bool", args = { "player", "tripoint", "bool" } },
            process_artifact = { rval = "bool", args = { "player", "tripoint" } },
            processing_speed = { rval = "int", args = { } },
            quiver_store_arrow = { rval = "int", args = { "item" } },
            ready_to_revive = { rval = "bool", args = { "tripoint" } },
            reduce_charges = { rval = "bool", args = { "int" } },
            reload = { rval = "bool", args = { "player", "int" } },
            reload_time = { rval = "int", args = { "player" } },
            reset_cable = { rval = nil, args = { "player" } },
            rotten = { rval = "bool", args = { } },
            set_auxiliary_mode = { rval = nil, args = { } },
            set_curammo = { rval = nil, args = { "item" } },
            set_gun_mode = { rval = nil, args = { "string" } },
            set_mtype = { rval = nil, args = { "mtype" } },
            set_relative_rot = { rval = nil, args = { "float" } },
            set_snippet = { rval = nil, args = { "string" } },
            set_var = { rval = nil, args = { "string", "int" } },
            set_var = { rval = nil, args = { "string", "int" } },
            set_var = { rval = nil, args = { "string", "string" } },
            sight_dispersion = { rval = "int", args = { "int" } },
            skill = { rval = "string", args = { } },
            spare_mag_size = { rval = "int", args = { } },
            stacks_with = { rval = "bool", args = { "item" } },
            symbol = { rval = "int", args = { } },
            tname = { rval = "string", args = { } },
            type_name = { rval = "string", args = { "int" } },
            unset_curammo = { rval = nil, args = { } },
            update_charger_gun_ammo = { rval = "bool", args = { } },
            use = { rval = nil, args = { } },
            volume = { rval = "int", args = { "bool", "bool" } },
            volume_contained = { rval = "int", args = { } },
            weap_skill = { rval = "string", args = { } },
            weapon_value = { rval = "int", args = { "player" } },
            weight = { rval = "int", args = { } },
        }
    },
    point = {
        by_value = true,
        has_equal = true,
        attributes = {
            x = {
                type = "int",
                writable = true
            },
            y = {
                type = "int",
                writable = true
            }
        },
        new = { "int", "int" },
        functions = {
        }
    },
    tripoint = {
        by_value = true,
        has_equal = true,
        attributes = {
            x = {
                type = "int",
                writable = true
            },
            y = {
                type = "int",
                writable = true
            },
            z = {
                type = "int",
                writable = true
            }
        },
        new = { "int", "int", "int" },
        functions = {
            serialize = {
                args = {},
                rval = "string"
            }
        }
    },
    uimenu = {
        attributes = {
            title = {
                type = "string",
                writable = true
            },
            selected = {
                type = "int",
                writable = false
            }
        },
        functions = {
            show = {
                args = {},
                rval = nil
            },
            query = {
                args = { "bool" },
                rval = nil
            },
            addentry = {
                args = { "string" },
                rval = nil
            }
        }
    },
    map = {
        attributes = {
        },
        functions = {
            accessible_furniture = { rval = "bool", args = { "tripoint", "tripoint", "int" } },
            accessible_items = { rval = "bool", args = { "tripoint", "tripoint", "int" } },
            add_camp = { rval = nil, args = { "tripoint", "string" } },
            add_corpse = { rval = nil, args = { "tripoint" } },
            add_spawn = { rval = nil, args = { "string", "int", "int", "int", "bool", "int", "int", "string" } },
            adjust_radiation = { rval = nil, args = { "int", "int", "int" } },
            adjust_radiation = { rval = nil, args = { "tripoint", "int" } },
            allow_camp = { rval = "bool", args = { "tripoint", "int" } },
            ambient_light_at = { rval = "float", args = { "int", "int" } },
            ambient_light_at = { rval = "float", args = { "tripoint" } },
            bash_rating = { rval = "int", args = { "int", "int", "int" } },
            bash_rating = { rval = "int", args = { "int", "tripoint" } },
            bash_resistance = { rval = "int", args = { "int", "int" } },
            bash_resistance = { rval = "int", args = { "tripoint" } },
            bash_strength = { rval = "int", args = { "int", "int" } },
            bash_strength = { rval = "int", args = { "tripoint" } },
            board_vehicle = { rval = nil, args = { "int", "int", "player" } },
            board_vehicle = { rval = nil, args = { "tripoint", "player" } },
            can_move_furniture = { rval = "bool", args = { "tripoint", "player" } },
            can_put_items = { rval = "bool", args = { "int", "int" } },
            can_put_items = { rval = "bool", args = { "tripoint" } },
            clear_path = { rval = "bool", args = { "tripoint", "tripoint", "int", "int", "int" } },
            clear_spawns = { rval = nil, args = { } },
            clear_traps = { rval = nil, args = { } },
            close_door = { rval = "bool", args = { "tripoint", "bool", "bool" } },
            collapse_at = { rval = nil, args = { "tripoint" } },
            collapse_check = { rval = "int", args = { "tripoint" } },
            coord_to_angle = { rval = "int", args = { "int", "int", "int", "int" } },
            could_see_items = { rval = "bool", args = { "tripoint", "player" } },
            create_spores = { rval = nil, args = { "tripoint", "Creature" } },
            creature_in_field = { rval = nil, args = { "Creature" } },
            creature_on_trap = { rval = nil, args = { "Creature", "bool" } },
            crush = { rval = nil, args = { "tripoint" } },
            decay_fields_and_scent = { rval = nil, args = { "int" } },
            delete_graffiti = { rval = nil, args = { "tripoint" } },
            delete_signage = { rval = nil, args = { "tripoint" } },
            destroy = { rval = nil, args = { "tripoint", "bool" } },
            destroy_furn = { rval = nil, args = { "tripoint", "bool" } },
            disarm_trap = { rval = nil, args = { "tripoint" } },
            displace_vehicle = { rval = "bool", args = { "tripoint", "tripoint", "bool" } },
            displace_water = { rval = "bool", args = { "int", "int" } },
            displace_water = { rval = "bool", args = { "tripoint" } },
            draw_fill_background = { rval = nil, args = { "int" } },
            draw_fill_background = { rval = nil, args = { "string" } },
            draw_line_furn = { rval = nil, args = { "int", "int", "int", "int", "int" } },
            draw_line_furn = { rval = nil, args = { "string", "int", "int", "int", "int" } },
            draw_line_ter = { rval = nil, args = { "int", "int", "int", "int", "int" } },
            draw_line_ter = { rval = nil, args = { "string", "int", "int", "int", "int" } },
            draw_rough_circle = { rval = nil, args = { "int", "int", "int", "int" } },
            draw_rough_circle = { rval = nil, args = { "string", "int", "int", "int" } },
            draw_rough_circle_furn = { rval = nil, args = { "int", "int", "int", "int" } },
            draw_rough_circle_furn = { rval = nil, args = { "string", "int", "int", "int" } },
            draw_square_furn = { rval = nil, args = { "int", "int", "int", "int", "int" } },
            draw_square_furn = { rval = nil, args = { "string", "int", "int", "int", "int" } },
            draw_square_ter = { rval = nil, args = { "int", "int", "int", "int", "int" } },
            draw_square_ter = { rval = nil, args = { "string", "int", "int", "int", "int" } },
            features = { rval = "string", args = { "int", "int" } },
            features = { rval = "string", args = { "tripoint" } },
            flammable_items_at = { rval = "bool", args = { "tripoint" } },
            free_volume = { rval = "int", args = { "int", "int" } },
            free_volume = { rval = "int", args = { "tripoint" } },
            furn = { rval = "int", args = { "int", "int" } },
            furn = { rval = "int", args = { "tripoint" } },
            furn_set = { rval = nil, args = { "int", "int", "int" } },
            furn_set = { rval = nil, args = { "int", "int", "string" } },
            furn_set = { rval = nil, args = { "tripoint", "int" } },
            furn_set = { rval = nil, args = { "tripoint", "string" } },
            furnname = { rval = "string", args = { "int", "int" } },
            furnname = { rval = "string", args = { "tripoint" } },
            generate = { rval = nil, args = { "int", "int", "int", "int" } },
            get_abs_sub = { rval = "tripoint", args = { } },
            get_furn = { rval = "string", args = { "int", "int" } },
            get_furn = { rval = "string", args = { "tripoint" } },
            get_radiation = { rval = "int", args = { "tripoint" } },
            get_signage = { rval = "string", args = { "tripoint" } },
            get_ter = { rval = "string", args = { "int", "int" } },
            get_ter = { rval = "string", args = { "tripoint" } },
            get_ter_harvest_season = { rval = "int", args = { "int", "int" } },
            get_ter_harvest_season = { rval = "int", args = { "tripoint" } },
            get_ter_harvestable = { rval = "string", args = { "int", "int" } },
            get_ter_harvestable = { rval = "string", args = { "tripoint" } },
            get_ter_transforms_into = { rval = "int", args = { "int", "int" } },
            get_ter_transforms_into = { rval = "int", args = { "tripoint" } },
            getabs = { rval = "point", args = { "int", "int" } },
            getabs = { rval = "point", args = { "point" } },
            getabs = { rval = "tripoint", args = { "tripoint" } },
            getlocal = { rval = "point", args = { "int", "int" } },
            getlocal = { rval = "point", args = { "point" } },
            getlocal = { rval = "tripoint", args = { "tripoint" } },
            getmapsize = { rval = "int", args = { } },
            graffiti_at = { rval = "string", args = { "tripoint" } },
            has_adjacent_furniture = { rval = "bool", args = { "tripoint" } },
            has_flag = { rval = "bool", args = { "string", "int", "int" } },
            has_flag = { rval = "bool", args = { "string", "tripoint" } },
            has_flag_furn = { rval = "bool", args = { "string", "int", "int" } },
            has_flag_furn = { rval = "bool", args = { "string", "tripoint" } },
            has_flag_ter = { rval = "bool", args = { "string", "int", "int" } },
            has_flag_ter = { rval = "bool", args = { "string", "tripoint" } },
            has_flag_ter_and_furn = { rval = "bool", args = { "string", "int", "int" } },
            has_flag_ter_and_furn = { rval = "bool", args = { "string", "tripoint" } },
            has_flag_ter_or_furn = { rval = "bool", args = { "string", "int", "int" } },
            has_flag_ter_or_furn = { rval = "bool", args = { "string", "tripoint" } },
            has_furn = { rval = "bool", args = { "int", "int" } },
            has_furn = { rval = "bool", args = { "tripoint" } },
            has_graffiti_at = { rval = "bool", args = { "tripoint" } },
            has_nearby_fire = { rval = "bool", args = { "tripoint", "int" } },
            has_zlevels = { rval = "bool", args = { } },
            hit_with_acid = { rval = "bool", args = { "tripoint" } },
            hit_with_fire = { rval = "bool", args = { "tripoint" } },
            i_at = { rval = "map_stack", args = { "tripoint" } },
            i_clear = { rval = nil, args = { "int", "int" } },
            i_clear = { rval = nil, args = { "tripoint" } },
            i_rem = { rval = "int", args = { "int", "int", "int" } },
            i_rem = { rval = "int", args = { "tripoint", "int" } },
            i_rem = { rval = nil, args = { "int", "int", "item" } },
            i_rem = { rval = nil, args = { "tripoint", "item" } },
            inbounds = { rval = "bool", args = { "int", "int" } },
            inbounds = { rval = "bool", args = { "int", "int", "int" } },
            inbounds = { rval = "bool", args = { "tripoint" } },
            is_bashable = { rval = "bool", args = { "int", "int" } },
            is_bashable = { rval = "bool", args = { "tripoint" } },
            is_bashable_furn = { rval = "bool", args = { "int", "int" } },
            is_bashable_furn = { rval = "bool", args = { "tripoint" } },
            is_bashable_ter = { rval = "bool", args = { "int", "int" } },
            is_bashable_ter = { rval = "bool", args = { "tripoint" } },
            is_bashable_ter_furn = { rval = "bool", args = { "int", "int" } },
            is_bashable_ter_furn = { rval = "bool", args = { "tripoint" } },
            is_divable = { rval = "bool", args = { "int", "int" } },
            is_divable = { rval = "bool", args = { "tripoint" } },
            is_full = { rval = "bool", args = { "tripoint", "int", "int" } },
            is_outside = { rval = "bool", args = { "int", "int" } },
            is_outside = { rval = "bool", args = { "tripoint" } },
            light_transparency = { rval = "float", args = { "tripoint" } },
            load = { rval = nil, args = { "int", "int", "int", "bool" } },
            make_rubble = { rval = nil, args = { "tripoint", "int", "bool", "int", "bool" } },
            marlossify = { rval = "bool", args = { "tripoint" } },
            max_volume = { rval = "int", args = { "int", "int" } },
            max_volume = { rval = "int", args = { "tripoint" } },
            mop_spills = { rval = nil, args = { "tripoint" } },
            moppable_items_at = { rval = "bool", args = { "tripoint" } },
            move_cost_ter_furn = { rval = "int", args = { "int", "int" } },
            move_cost_ter_furn = { rval = "int", args = { "tripoint" } },
            name = { rval = "string", args = { "int", "int" } },
            name = { rval = "string", args = { "tripoint" } },
            open_door = { rval = "bool", args = { "tripoint", "bool", "bool" } },
            pl_sees = { rval = "bool", args = { "int", "int", "int" } },
            pl_sees = { rval = "bool", args = { "tripoint", "int" } },
            place_gas_pump = { rval = nil, args = { "int", "int", "int" } },
            place_npc = { rval = "int", args = { "int", "int", "string" } },
            place_toilet = { rval = nil, args = { "int", "int", "int" } },
            place_vending = { rval = nil, args = { "int", "int", "string" } },
            post_process = { rval = nil, args = { "int" } },
            process_active_items = { rval = nil, args = { } },
            process_fields = { rval = "bool", args = { } },
            random_outdoor_tile = { rval = "point", args = { } },
            remove_trap = { rval = nil, args = { "tripoint" } },
            rotate = { rval = nil, args = { "int" } },
            save = { rval = nil, args = { } },
            sees = { rval = "bool", args = { "tripoint", "tripoint", "int" } },
            sees_some_items = { rval = "bool", args = { "tripoint", "player" } },
            set = { rval = nil, args = { "int", "int", "int", "int" } },
            set = { rval = nil, args = { "int", "int", "string", "string" } },
            set = { rval = nil, args = { "tripoint", "int", "int" } },
            set = { rval = nil, args = { "tripoint", "string", "string" } },
            set_graffiti = { rval = nil, args = { "tripoint", "string" } },
            set_radiation = { rval = nil, args = { "int", "int", "int" } },
            set_radiation = { rval = nil, args = { "tripoint", "int" } },
            set_signage = { rval = nil, args = { "tripoint", "string" } },
            set_temperature = { rval = nil, args = { "int", "int", "int" } },
            set_temperature = { rval = nil, args = { "tripoint", "int" } },
            shift = { rval = nil, args = { "int", "int" } },
            smash_items = { rval = nil, args = { "tripoint", "int" } },
            spawn_artifact = { rval = nil, args = { "tripoint" } },
            spawn_item = { rval = nil, args = { "int", "int", "string", "int", "int", "int", "int", "bool" } },
            spawn_item = { rval = nil, args = { "tripoint", "string", "int", "int", "int", "int", "bool" } },
            spawn_monsters = { rval = nil, args = { "bool" } },
            stored_volume = { rval = "int", args = { "int", "int" } },
            stored_volume = { rval = "int", args = { "tripoint" } },
            ter = { rval = "int", args = { "int", "int" } },
            ter = { rval = "int", args = { "tripoint" } },
            ter_set = { rval = nil, args = { "int", "int", "int" } },
            ter_set = { rval = nil, args = { "int", "int", "string" } },
            ter_set = { rval = nil, args = { "tripoint", "int" } },
            ter_set = { rval = nil, args = { "tripoint", "string" } },
            tername = { rval = "string", args = { "int", "int" } },
            tername = { rval = "string", args = { "tripoint" } },
            trans = { rval = "bool", args = { "int", "int" } },
            trans = { rval = "bool", args = { "tripoint" } },
            translate = { rval = nil, args = { "int", "int" } },
            translate_radius = { rval = nil, args = { "int", "int", "float", "tripoint" } },
            trigger_rc_items = { rval = nil, args = { "string" } },
            unboard_vehicle = { rval = nil, args = { "int", "int" } },
            unboard_vehicle = { rval = nil, args = { "tripoint" } },
            valid_move = { rval = "bool", args = { "tripoint", "tripoint", "bool", "bool" } },
            veh_part_coordinates = { rval = "point", args = { "int", "int" } },
            veh_part_coordinates = { rval = "point", args = { "tripoint" } },
            vertical_shift = { rval = nil, args = { "int" } },
        }
    },
    ter_t = {
        attributes = {
            name = {
                type = "string",
                writable = false
            },
            id = {
                type = "string",
                writable = false
            },
            loadid = {
                type = "int",
                writable = false
            },
            movecost = {
                type = "int",
                writable = false
            }
        },
        functions = {
        }
    },
    Creature = {
        attributes = {
            dex_cur = { type = "int", writable = true },
            dex_max = { type = "int", writable = true },
            int_cur = { type = "int", writable = true },
            int_max = { type = "int", writable = true },
            pain = { type = "int", writable = true },
            per_cur = { type = "int", writable = true },
            per_max = { type = "int", writable = true },
            str_cur = { type = "int", writable = true },
            str_max = { type = "int", writable = true },
            underwater = { type = "bool", writable = true },
        },
        functions = {
            add_effect = { rval = nil, args = { "string", "int" } },
            basic_symbol_color = { rval = "int", args = { } },
            check_dead_state = { rval = nil, args = { } },
            clear_effects = { rval = nil, args = { } },
            deal_melee_attack = { rval = "int", args = { "Creature", "int" } },
            digging = { rval = "bool", args = { } },
            get_armor_bash_bonus = { rval = "int", args = { } },
            get_armor_cut_bonus = { rval = "int", args = { } },
            get_bash_bonus = { rval = "int", args = { } },
            get_bash_mult = { rval = "float", args = { } },
            get_block_bonus = { rval = "int", args = { } },
            get_cut_bonus = { rval = "int", args = { } },
            get_cut_mult = { rval = "float", args = { } },
            get_dex = { rval = "int", args = { } },
            get_dex_base = { rval = "int", args = { } },
            get_dex_bonus = { rval = "int", args = { } },
            get_dodge = { rval = "int", args = { } },
            get_dodge_base = { rval = "int", args = { } },
            get_dodge_bonus = { rval = "int", args = { } },
            get_effect_dur = { rval = "int", args = { "string" } },
            get_effect_int = { rval = "int", args = { "string" } },
            get_grab_resist = { rval = "int", args = { } },
            get_healthy = { rval = "int", args = { } },
            get_healthy_mod = { rval = "int", args = { } },
            get_hit = { rval = "int", args = { } },
            get_hit_base = { rval = "int", args = { } },
            get_hit_bonus = { rval = "int", args = { } },
            get_int = { rval = "int", args = { } },
            get_int_base = { rval = "int", args = { } },
            get_int_bonus = { rval = "int", args = { } },
            get_killer = { rval = "Creature", args = { } },
            get_material = { rval = "string", args = { } },
            get_melee = { rval = "int", args = { } },
            get_melee_quiet = { rval = "bool", args = { } },
            get_num_blocks = { rval = "int", args = { } },
            get_num_blocks_bonus = { rval = "int", args = { } },
            get_num_dodges = { rval = "int", args = { } },
            get_num_dodges_bonus = { rval = "int", args = { } },
            get_per = { rval = "int", args = { } },
            get_per_base = { rval = "int", args = { } },
            get_per_bonus = { rval = "int", args = { } },
            get_speed = { rval = "int", args = { } },
            get_speed_base = { rval = "int", args = { } },
            get_speed_bonus = { rval = "int", args = { } },
            get_str = { rval = "int", args = { } },
            get_str_base = { rval = "int", args = { } },
            get_str_bonus = { rval = "int", args = { } },
            get_throw_resist = { rval = "int", args = { } },
            get_value = { rval = "string", args = { "string" } },
            has_effect = { rval = "bool", args = { "string" } },
            has_trait = { rval = "bool", args = { "string" } },
            in_sleep_state = { rval = "bool", args = { } },
            is_fake = { rval = "bool", args = { } },
            is_immune = { rval = "bool", args = { "string" } },
            is_monster = { rval = "bool", args = { } },
            is_npc = { rval = "bool", args = { } },
            is_player = { rval = "bool", args = { } },
            is_symbol_highlighted = { rval = "bool", args = { } },
            is_warm = { rval = "bool", args = { } },
            melee_attack = { rval = nil, args = { "Creature", "bool" } },
            mod_bash_bonus = { rval = nil, args = { "int" } },
            mod_block_bonus = { rval = nil, args = { "int" } },
            mod_cut_bonus = { rval = nil, args = { "int" } },
            mod_dex_bonus = { rval = nil, args = { "int" } },
            mod_dodge_bonus = { rval = nil, args = { "int" } },
            mod_healthy = { rval = nil, args = { "int" } },
            mod_healthy_mod = { rval = nil, args = { "int" } },
            mod_hit_bonus = { rval = nil, args = { "int" } },
            mod_int_bonus = { rval = nil, args = { "int" } },
            mod_moves = { rval = nil, args = { "int" } },
            mod_pain = { rval = nil, args = { "int" } },
            mod_per_bonus = { rval = nil, args = { "int" } },
            mod_speed_bonus = { rval = nil, args = { "int" } },
            mod_stat = { rval = nil, args = { "string", "int" } },
            mod_str_bonus = { rval = nil, args = { "int" } },
            move_effects = { rval = "bool", args = { } },
            normalize = { rval = nil, args = { } },
            pos3 = { rval = "tripoint", args = { } },
            process_effects = { rval = nil, args = { } },
            process_turn = { rval = nil, args = { } },
            remove_effect = { rval = "bool", args = { "string" } },
            remove_value = { rval = nil, args = { "string" } },
            reset = { rval = nil, args = { } },
            reset_bonuses = { rval = nil, args = { } },
            reset_stats = { rval = nil, args = { } },
            sees = { rval = "bool", args = { "Creature" } },
            sees = { rval = "bool", args = { "int", "int" } },
            sees = { rval = "bool", args = { "point" } },
            sees = { rval = "bool", args = { "tripoint" } },
            set_armor_bash_bonus = { rval = nil, args = { "int" } },
            set_armor_cut_bonus = { rval = nil, args = { "int" } },
            set_bash_bonus = { rval = nil, args = { "int" } },
            set_bash_mult = { rval = nil, args = { "float" } },
            set_block_bonus = { rval = nil, args = { "int" } },
            set_cut_bonus = { rval = nil, args = { "int" } },
            set_cut_mult = { rval = nil, args = { "float" } },
            set_dex_bonus = { rval = nil, args = { "int" } },
            set_dodge_bonus = { rval = nil, args = { "int" } },
            set_fake = { rval = nil, args = { "bool" } },
            set_grab_resist = { rval = nil, args = { "int" } },
            set_healthy = { rval = nil, args = { "int" } },
            set_healthy_mod = { rval = nil, args = { "int" } },
            set_hit_bonus = { rval = nil, args = { "int" } },
            set_int_bonus = { rval = nil, args = { "int" } },
            set_melee_quiet = { rval = nil, args = { "bool" } },
            set_moves = { rval = nil, args = { "int" } },
            set_num_blocks_bonus = { rval = nil, args = { "int" } },
            set_num_dodges_bonus = { rval = nil, args = { "int" } },
            set_per_bonus = { rval = nil, args = { "int" } },
            set_speed_base = { rval = nil, args = { "int" } },
            set_speed_bonus = { rval = nil, args = { "int" } },
            set_str_bonus = { rval = nil, args = { "int" } },
            set_throw_resist = { rval = nil, args = { "int" } },
            set_value = { rval = nil, args = { "string", "string" } },
            symbol = { rval = "string", args = { } },
            symbol_color = { rval = "int", args = { } },
            uncanny_dodge = { rval = "bool", args = { } },
            update_health = { rval = nil, args = { "int" } },
            weight_capacity = { rval = "int", args = { } },
        }
    },
    monster = {
        parent = "Creature",
        attributes = {
            anger = { type = "int", writable = true },
            def_chance = { type = "int", writable = true },
            friendly = { type = "int", writable = true },
            hallucination = { type = "bool", writable = true },
            ignoring = { type = "int", writable = true },
            made_footstep = { type = "bool", writable = true },
            mission_id = { type = "int", writable = true },
            morale = { type = "int", writable = true },
            no_corpse_quiet = { type = "bool", writable = true },
            no_extra_death_drops = { type = "bool", writable = true },
            staircount = { type = "int", writable = true },
            type = { type = "mtype" },
            unique_name = { type = "string", writable = true },
            wander_pos = { type = "tripoint", writable = true },
            wandf = { type = "int", writable = true },
        },
        functions = {
            attack_at = { rval = "bool", args = { "tripoint" } },
            attack_target = { rval = "Creature", args = { } },
            bash_at = { rval = "bool", args = { "tripoint" } },
            bash_estimate = { rval = "int", args = { } },
            bash_skill = { rval = "int", args = { } },
            basic_symbol_color = { rval = "int", args = { } },
            calc_movecost = { rval = "int", args = { "tripoint", "tripoint" } },
            can_act = { rval = "bool", args = { } },
            can_drown = { rval = "bool", args = { } },
            can_hear = { rval = "bool", args = { } },
            can_move_to = { rval = "bool", args = { "tripoint" } },
            can_see = { rval = "bool", args = { } },
            can_submerge = { rval = "bool", args = { } },
            can_upgrade = { rval = "bool", args = { } },
            color_with_effects = { rval = "int", args = { } },
            deal_melee_attack = { rval = "int", args = { "Creature", "int" } },
            debug = { rval = nil, args = { "player" } },
            die = { rval = nil, args = { "Creature" } },
            die_in_explosion = { rval = nil, args = { "Creature" } },
            digging = { rval = "bool", args = { } },
            disp_name = { rval = "string", args = { "bool" } },
            dodge_hit = { rval = nil, args = { "Creature", "int" } },
            dodge_roll = { rval = "int", args = { } },
            drop_items_on_death = { rval = nil, args = { } },
            explode = { rval = nil, args = { } },
            fall_damage = { rval = "int", args = { } },
            footsteps = { rval = nil, args = { "tripoint" } },
            friendly_move = { rval = nil, args = { } },
            get_dodge = { rval = "int", args = { } },
            get_hp = { rval = "int", args = { } },
            get_hp_max = { rval = "int", args = { } },
            get_last_load = { rval = "int", args = { } },
            get_material = { rval = "string", args = { } },
            get_melee = { rval = "int", args = { } },
            group_bash_skill = { rval = "int", args = { "tripoint" } },
            has_weapon = { rval = "bool", args = { } },
            heal = { rval = nil, args = { "int" } },
            hit_roll = { rval = "int", args = { } },
            hp_percentage = { rval = "int", args = { } },
            init_from_item = { rval = nil, args = { "item" } },
            is_dead = { rval = "bool", args = { } },
            is_dead_state = { rval = "bool", args = { } },
            is_elec_immune = { rval = "bool", args = { } },
            is_fleeing = { rval = "bool", args = { "player" } },
            is_hallucination = { rval = "bool", args = { } },
            is_monster = { rval = "bool", args = { } },
            is_on_ground = { rval = "bool", args = { } },
            is_symbol_highlighted = { rval = "bool", args = { } },
            is_underwater = { rval = "bool", args = { } },
            is_warm = { rval = "bool", args = { } },
            knock_back_from = { rval = nil, args = { "tripoint" } },
            load_info = { rval = nil, args = { "string" } },
            made_of = { rval = "bool", args = { "string" } },
            make_ally = { rval = nil, args = { "monster" } },
            make_friendly = { rval = nil, args = { } },
            make_fungus = { rval = "bool", args = { } },
            move = { rval = nil, args = { } },
            move_effects = { rval = "bool", args = { } },
            move_target = { rval = "tripoint", args = { } },
            move_to = { rval = "bool", args = { "tripoint", "bool" } },
            name = { rval = "string", args = { "int" } },
            name_with_armor = { rval = "string", args = { } },
            on_dodge = { rval = nil, args = { "Creature", "int" } },
            poly = { rval = nil, args = { "mtype" } },
            pos = { rval = "tripoint", args = { } },
            posx = { rval = "int", args = { } },
            posy = { rval = "int", args = { } },
            posz = { rval = "int", args = { } },
            power_rating = { rval = "float", args = { } },
            process_effects = { rval = nil, args = { } },
            process_triggers = { rval = nil, args = { } },
            reset_last_load = { rval = nil, args = { } },
            reset_special = { rval = nil, args = { "int" } },
            reset_special_rng = { rval = nil, args = { "int" } },
            scent_move = { rval = "tripoint", args = { } },
            set_hp = { rval = nil, args = { "int" } },
            set_last_load = { rval = nil, args = { "int" } },
            set_special = { rval = nil, args = { "int", "int" } },
            setpos = { rval = "bool", args = { "tripoint", "bool" } },
            shift = { rval = nil, args = { "int", "int" } },
            sight_range = { rval = "int", args = { "int" } },
            skin_name = { rval = "string", args = { } },
            spawn = { rval = nil, args = { "tripoint" } },
            stumble = { rval = nil, args = { "bool" } },
            symbol = { rval = "string", args = { } },
            symbol_color = { rval = "int", args = { } },
            turns_to_reach = { rval = "int", args = { "int", "int" } },
            update_check = { rval = nil, args = { } },
            wander = { rval = "bool", args = { } },
            wander_next = { rval = "tripoint", args = { } },
            wander_to = { rval = nil, args = { "tripoint", "int" } },
            will_reach = { rval = "bool", args = { "int", "int" } },
        }
    },
    mtype = {
        attributes = {
            agro = { type = "int", writable = true },
            armor_bash = { type = "int", writable = true },
            armor_cut = { type = "int", writable = true },
            base_upgrade_chance = { type = "float", writable = true },
            color = { type = "int", writable = true },
            death_drops = { type = "string", writable = true },
            def_chance = { type = "int", writable = true },
            description = { type = "string", writable = true },
            difficulty = { type = "int", writable = true },
            half_life = { type = "int", writable = true },
            hp = { type = "int", writable = true },
            id = { type = "string", writable = true },
            luminance = { type = "float", writable = true },
            mat = { type = "string", writable = true },
            melee_cut = { type = "int", writable = true },
            melee_dice = { type = "int", writable = true },
            melee_sides = { type = "int", writable = true },
            melee_skill = { type = "int", writable = true },
            morale = { type = "int", writable = true },
            sk_dodge = { type = "int", writable = true },
            speed = { type = "int", writable = true },
            sym = { type = "string", writable = true },
            upgrade_min = { type = "int", writable = true },
            upgrades_into = { type = "string", writable = true },
            vision_day = { type = "int", writable = true },
            vision_night = { type = "int", writable = true },
        },
        functions = {
            has_flag = { rval = "bool", args = { "string" } },
            in_category = { rval = "bool", args = { "string" } },
            in_species = { rval = "bool", args = { "int" } },
            in_species = { rval = "bool", args = { "string" } },
            nname = { rval = "string", args = { "int" } },
            same_species = { rval = "bool", args = { "mtype" } },
            set_flag = { rval = nil, args = { "string", "bool" } },
        }
    },
    mongroup = {
        attributes = {
            posx = {
                type = "int",
                writable = true
            },
            posy = {
                type = "int",
                writable = true
            },
            posz = {
                type = "int",
                writable = true
            },
            tx = {
                type = "int",
                writable = false
            },
            ty = {
                type = "int",
                writable = false
            },
            dying = {
                type = "bool",
                writable = true
            },
            horde = {
                type = "bool",
                writable = true
            },
            diffuse = {
                type = "bool",
                writable = true
            },
            radius = {
                type = "int",
                writable = true
            },
            population = {
                type = "int",
                writable = true
            }
        },
        functions = {
            set_target = {
                args = {"int", "int"},
                rval = nil
            },
            inc_interest = {
                args = {"int"},
                rval = nil
            },
            dec_interest = {
                args = {"int"},
                rval = nil
            },
            set_interest = {
                args = {"int"},
                rval = nil
            }
        }
    },
    overmap = {
        attributes = {
        },
        functions = {
            get_bottom_border = {
                args = {},
                rval = "int"
            },
            get_top_border = {
                args = {},
                rval = "int"
            },
            get_left_border = {
                args = {},
                rval = "int"
            },
            get_right_border = {
                args = {},
                rval = "int"
            },
        }
    },
    itype = {
        attributes = {
            color = { type = "int", writable = true },
            description = { type = "string", writable = true },
            id = { type = "string" },
            light_emission = { type = "int", writable = true },
            m_to_hit = { type = "int", writable = true },
            melee_cut = { type = "int", writable = true },
            melee_dam = { type = "int", writable = true },
            price = { type = "int", writable = true },
            snippet_category = { type = "string", writable = true },
            stack_size = { type = "int", writable = true },
            sym = { type = "int", writable = true },
            volume = { type = "int", writable = true },
            weight = { type = "int", writable = true },
        },
        functions = {
            can_use = { rval = "bool", args = { "string" } },
            charges_to_use = { rval = "int", args = { } },
            count_by_charges = { rval = "bool", args = { } },
            explode_in_fire = { rval = "bool", args = { } },
            get_item_type_string = { rval = "string", args = { } },
            has_use = { rval = "bool", args = { } },
            invoke = { rval = "int", args = { "player", "item", "point" } },
            invoke = { rval = "int", args = { "player", "item", "point", "string" } },
            invoke = { rval = "int", args = { "player", "item", "tripoint" } },
            invoke = { rval = "int", args = { "player", "item", "tripoint", "string" } },
            is_artifact = { rval = "bool", args = { } },
            is_food = { rval = "bool", args = { } },
            is_tool = { rval = "bool", args = { } },
            maximum_charges = { rval = "int", args = { } },
            nname = { rval = "string", args = { "int" } },
            tick = { rval = "int", args = { "player", "item", "point" } },
            tick = { rval = "int", args = { "player", "item", "tripoint" } },
        }
    },
    it_comest = {
        parent = "itype",
        attributes = {
            quench = {
                type = "int",
                writable = true
            },
            nutrition = {
                type = "int",
                cpp_name = "nutr",
                writable = true
            },
            spoils_in = {
                type = "int",
                cpp_name = "spoils",
                writable = true
            },
            addiction_potential = {
                type = "int",
                cpp_name = "addict",
                writable = true
            },
            def_charges = {
                type = "int",
                writable = true
            },
            stim = {
                type = "int",
                writable = true
            },
            healthy = {
                type = "int",
                writable = true
            },
            brewtime = {
                type = "int",
                writable = true
            },
            fun = {
                type = "int",
                writable = true
            },
            tool = {
                type = "string",
                writable = true
            },
            comestible_type = {
                type = "string",
                cpp_name = "comesttype",
                writable = true
            }
        },
        functions = {
        }
    },
    it_tool = {
        parent = "itype",
        attributes = {
            ammo_id = {
                type = "string",
                writable = true
            },
            max_charges = {
                type = "int",
                writable = true
            },
            def_charges = {
                type = "int",
                writable = true
            },
            charges_per_use = {
                type = "int",
                writable = true
            },
            turns_per_charge = {
                type = "int",
                writable = true
            }
        },
        functions = {
        }
    }
}

global_functions = {
    add_msg = {
        cpp_name = "add_msg_wrapper",
        args     = { "string" },
        argnames = { "message" },
        rval = nil,
        desc = "Write a message to the game's standard message window."
    },
    popup = {
        cpp_name = "popup_wrapper",
        args = { "string" },
        rval = nil
    },
    string_input_popup = {
        cpp_name = "string_input_popup",
        args = { "string", "int", "string" },
        rval = "string"
    },
    create_uimenu = {
        cpp_name = "create_uimenu",
        args = {},
        rval = "uimenu"
    },
    get_terrain_type = {
        cpp_name = "get_terrain_type",
        args = {"int"},
        rval = "ter_t"
    },
    rng = {
        cpp_name = "rng",
        args = {"int", "int"},
        rval = "int"
    },
    one_in = {
        cpp_name = "one_in",
        args = {"int"},
        rval = "bool"
    },
    distance = {
        cpp_name = "rl_dist",
        args = {"int", "int", "int", "int"},
        rval = "int"
    },
    trig_dist = {
        cpp_name = "trig_dist",
        args = {"int", "int", "int", "int"},
        rval = "int"
    },
    remove_item = {
        cpp_name = "game_remove_item",
        args = {"tripoint", "item"},
        rval = nil
    },
    get_current_overmap = {
        cpp_name = "get_current_overmap",
        args = { },
        rval = "overmap"
    },
    add_item_to_group = {
        cpp_name = "item_controller->add_item_to_group",
        args = { "string", "string", "int" },
        rval = "bool"
    },
    get_comestible_type = {
        cpp_name = "get_comestible_type",
        args = { "string" },
        rval = "it_comest"
    },
    revive_corpse = {
        cpp_name = "g->revive_corpse",
        args = { "tripoint", "item" },
        rval = "bool"
    },
    zombie = {
        cpp_name = "g->zombie",
        args = { "int" },
        rval = "monster",
        desc = "Returns a reference to the zombie of given index (starts at 0), use num_zombies to get the number of zombies. Parameters must be in the range [0, num_zombies-1]"
    },
    num_zombies = {
        cpp_name = "g->num_zombies",
        args = {},
        rval = "int",
        desc = "Returns the number of monsters currently existing in the reailty bubble."
    },
    create_monster = {
        cpp_name = "create_monster",
        args = { "string", "tripoint" },
        rval = "monster",
        desc = "Creates and spawns a new monster of given type. Returns a refernce to it, *or* nil if it could not be spawned."
    },
    get_tool_type = {
        cpp_name = "get_tool_type",
        args = { "string" },
        rval = "it_tool"
    }
}

--[[
Currently, for each function in each class, the bindings generator creates a matching function in
each of the parent classes. For example is_player, which is defined in Creature and player.
Because it's in Creature and monster inherits it from there, the generator adds a wrapper to the
metatable of the monster class that calls is_player on a monster object.
However, it creates the same "wrapper" for the player class (same scenario: it inherits it from
Creature).
Now player::is_player is wrapped twice: once through the heritage from Creature and once on its own.

The following snippet tries to correct this. It simply removes all the redundantly declared
functions in the subclasses.
--]]

for name, value in pairs(classes) do
    -- Collect all defined functions of the *parent* classes in this table
    local existing = { };
    value = classes[value.parent]
    while value do
        for fname, func in pairs(value.functions) do
            local n = fname .. "_" .. table.concat(func.args, "|")
            existing[n] = true
        end
        value = classes[value.parent]
    end
    -- Now back to the actual class, remove all the functions that are in the table
    -- and therefor exist in at least on of the parent classes.
    value = classes[name]
    for fname, func in pairs(value.functions) do
        local n = fname .. "_" .. table.concat(func.args, "|")
        if existing[n] then
            value.functions[fname] = nil
        end
    end
end
