// This file is autogenerated by qmake. It imports static plugin classes for
// static plugins specified using QTPLUGIN and QT_PLUGIN_CLASS.<plugin> variables.
#include <QtCore/QtPlugin>
#ifdef _WIN32
    Q_IMPORT_PLUGIN(QWindowsIntegrationPlugin)
#endif
