#pragma once
#ifndef STRING_CONSTS_H
#define STRING_CONSTS_H

static const activity_id ACT_BURROW("ACT_BURROW");
static const activity_id ACT_CRAFT("ACT_CRAFT");
static const activity_id ACT_FILL_LIQUID("ACT_FILL_LIQUID");
static const activity_id ACT_PICKAXE("ACT_PICKAXE");
static const activity_id ACT_DROP("ACT_DROP");
static const activity_id ACT_STASH("ACT_STASH");
static const activity_id ACT_PULP("ACT_PULP");
static const activity_id ACT_GAME("ACT_GAME");
static const activity_id ACT_GENERIC_GAME("ACT_GENERIC_GAME");
static const activity_id ACT_START_FIRE("ACT_START_FIRE");
static const activity_id ACT_VIBE("ACT_VIBE");
static const activity_id ACT_HAND_CRANK("ACT_HAND_CRANK");
static const activity_id ACT_OXYTORCH("ACT_OXYTORCH");
static const activity_id ACT_AIM("ACT_AIM");
static const activity_id ACT_WEAR("ACT_WEAR");
static const activity_id ACT_MULTIPLE_FISH("ACT_MULTIPLE_FISH");
static const activity_id ACT_MULTIPLE_CONSTRUCTION("ACT_MULTIPLE_CONSTRUCTION");
static const activity_id ACT_MULTIPLE_BUTCHER("ACT_MULTIPLE_BUTCHER");
static const activity_id ACT_MULTIPLE_FARM("ACT_MULTIPLE_FARM");
static const activity_id ACT_FETCH_REQUIRED("ACT_FETCH_REQUIRED");
static const activity_id ACT_BUILD("ACT_BUILD");
static const activity_id ACT_EAT_MENU("ACT_EAT_MENU");
static const activity_id ACT_VEHICLE_DECONSTRUCTION("ACT_VEHICLE_DECONSTRUCTION");
static const activity_id ACT_VEHICLE_REPAIR("ACT_VEHICLE_REPAIR");
static const activity_id ACT_MULTIPLE_CHOP_TREES("ACT_MULTIPLE_CHOP_TREES");
static const activity_id ACT_CONSUME_FOOD_MENU("ACT_CONSUME_FOOD_MENU");
static const activity_id ACT_CONSUME_DRINK_MENU("ACT_CONSUME_DRINK_MENU");
static const activity_id ACT_CONSUME_MEDS_MENU("ACT_CONSUME_MEDS_MENU");
static const activity_id ACT_MOVE_ITEMS("ACT_MOVE_ITEMS");
static const activity_id ACT_MOVE_LOOT("ACT_MOVE_LOOT");
static const activity_id ACT_ADV_INVENTORY("ACT_ADV_INVENTORY");
static const activity_id ACT_ARMOR_LAYERS("ACT_ARMOR_LAYERS");
static const activity_id ACT_ATM("ACT_ATM");
static const activity_id ACT_CRACKING("ACT_CRACKING");
static const activity_id ACT_FISH("ACT_FISH");
static const activity_id ACT_REPAIR_ITEM("ACT_REPAIR_ITEM");
static const activity_id ACT_BUTCHER("ACT_BUTCHER");
static const activity_id ACT_BUTCHER_FULL("ACT_BUTCHER_FULL");
static const activity_id ACT_TRAVELLING("ACT_TRAVELLING");
static const activity_id ACT_AUTODRIVE("ACT_AUTODRIVE");
static const activity_id ACT_FIELD_DRESS("ACT_FIELD_DRESS");
static const activity_id ACT_SKIN("ACT_SKIN");
static const activity_id ACT_QUARTER("ACT_QUARTER");
static const activity_id ACT_DISMEMBER("ACT_DISMEMBER");
static const activity_id ACT_DISSECT("ACT_DISSECT");
static const activity_id ACT_HACKSAW("ACT_HACKSAW");
static const activity_id ACT_CHOP_TREE("ACT_CHOP_TREE");
static const activity_id ACT_CHOP_LOGS("ACT_CHOP_LOGS");
static const activity_id ACT_TIDY_UP("ACT_TIDY_UP");
static const activity_id ACT_CHOP_PLANKS("ACT_CHOP_PLANKS");
static const activity_id ACT_JACKHAMMER("ACT_JACKHAMMER");
static const activity_id ACT_FIND_MOUNT("ACT_FIND_MOUNT");
static const activity_id ACT_DIG("ACT_DIG");
static const activity_id ACT_DIG_CHANNEL("ACT_DIG_CHANNEL");
static const activity_id ACT_FILL_PIT("ACT_FILL_PIT");
static const activity_id ACT_MULTIPLE_CHOP_PLANKS("ACT_MULTIPLE_CHOP_PLANKS");
static const activity_id ACT_FERTILIZE_PLOT("ACT_FERTILIZE_PLOT");
static const activity_id ACT_TRY_SLEEP("ACT_TRY_SLEEP");
static const activity_id ACT_OPERATION("ACT_OPERATION");
static const activity_id ACT_ROBOT_CONTROL("ACT_ROBOT_CONTROL");
static const activity_id ACT_TREE_COMMUNION("ACT_TREE_COMMUNION");
static const activity_id ACT_READ("ACT_READ");
static const activity_id ACT_WAIT_STAMINA("ACT_WAIT_STAMINA");
static const activity_id ACT_STUDY_SPELL("ACT_STUDY_SPELL");
static const activity_id ACT_PICKUP("ACT_PICKUP");
static const activity_id ACT_FIRSTAID("ACT_FIRSTAID");
static const activity_id ACT_FORAGE("ACT_FORAGE");
static const activity_id ACT_HOTWIRE_CAR("ACT_HOTWIRE_CAR");
static const activity_id ACT_LONGSALVAGE("ACT_LONGSALVAGE");
static const activity_id ACT_MAKE_ZLAVE("ACT_MAKE_ZLAVE");
static const activity_id ACT_RELOAD("ACT_RELOAD");
static const activity_id ACT_TRAIN("ACT_TRAIN");
static const activity_id ACT_CHURN("ACT_CHURN");
static const activity_id ACT_VEHICLE("ACT_VEHICLE");
static const activity_id ACT_START_ENGINES("ACT_START_ENGINES");
static const activity_id ACT_OPEN_GATE("ACT_OPEN_GATE");
static const activity_id ACT_HEATING("ACT_HEATING");
static const activity_id ACT_MEND_ITEM("ACT_MEND_ITEM");
static const activity_id ACT_GUNMOD_ADD("ACT_GUNMOD_ADD");
static const activity_id ACT_TOOLMOD_ADD("ACT_TOOLMOD_ADD");
static const activity_id ACT_MEDITATE("ACT_MEDITATE");
static const activity_id ACT_SPELLCASTING("ACT_SPELLCASTING");
static const activity_id ACT_HACKING("ACT_HACKING");
static const activity_id ACT_CLEAR_RUBBLE("ACT_CLEAR_RUBBLE");
static const activity_id ACT_WAIT("ACT_WAIT");
static const activity_id ACT_WAIT_WEATHER("ACT_WAIT_WEATHER");
static const activity_id ACT_WAIT_NPC("ACT_WAIT_NPC");
static const activity_id ACT_SOCIALIZE("ACT_SOCIALIZE");
static const activity_id ACT_DISASSEMBLE("ACT_DISASSEMBLE");
static const activity_id ACT_WASH("ACT_WASH");
static const activity_id ACT_PLAY_WITH_PET("ACT_PLAY_WITH_PET");
static const activity_id ACT_SHAVE("ACT_SHAVE");
static const activity_id ACT_HAIRCUT("ACT_HAIRCUT");
static const activity_id ACT_UNLOAD_MAG("ACT_TRAIN");
static const activity_id ACT_MIND_SPLICER("ACT_MIND_SPLICER");

static const bionic_id bio_ads( "bio_ads" );
static const bionic_id bio_armor_arms( "bio_armor_arms" );
static const bionic_id bio_armor_eyes( "bio_armor_eyes" );
static const bionic_id bio_armor_head( "bio_armor_head" );
static const bionic_id bio_armor_legs( "bio_armor_legs" );
static const bionic_id bio_armor_torso( "bio_armor_torso" );
static const bionic_id bio_carbon( "bio_carbon" );
static const bionic_id bio_climate( "bio_climate" );
static const bionic_id bio_cloak( "bio_cloak" );
static const bionic_id bio_cqb( "bio_cqb" );
static const bionic_id bio_earplugs( "bio_earplugs" );
static const bionic_id bio_ears( "bio_ears" );
static const bionic_id bio_eye_optic( "bio_eye_optic" );
static const bionic_id bio_faraday( "bio_faraday" );
static const bionic_id bio_flashlight( "bio_flashlight" );
static const bionic_id bio_ground_sonar( "bio_ground_sonar" );
static const bionic_id bio_gills( "bio_gills" );
static const bionic_id bio_heatsink( "bio_heatsink" );
static const bionic_id bio_jointservo( "bio_jointservo" );
static const bionic_id bio_laser( "bio_laser" );
static const bionic_id bio_lighter( "bio_lighter" );
static const bionic_id bio_membrane( "bio_membrane" );
static const bionic_id bio_memory( "bio_memory" );
static const bionic_id bio_recycler( "bio_recycler" );
static const bionic_id bio_soporific( "bio_soporific" );
static const bionic_id bio_speed( "bio_speed" );
static const bionic_id bio_synaptic_regen( "bio_synaptic_regen" );
static const bionic_id bio_syringe( "bio_syringe" );
static const bionic_id bio_tattoo_led( "bio_tattoo_led" );
static const bionic_id bio_tools( "bio_tools" );
static const bionic_id bio_ups( "bio_ups" );
static const bionic_id bio_uncanny_dodge( "bio_uncanny_dodge" );
static const bionic_id bio_watch( "bio_watch" );
// Aftershock stuff!
static const bionic_id afs_bio_linguistic_coprocessor( "afs_bio_linguistic_coprocessor" );

static const efftype_id effect_adrenaline( "adrenaline" );
static const efftype_id effect_alarm_clock( "alarm_clock" );
static const efftype_id effect_bandaged( "bandaged" );
static const efftype_id effect_beartrap( "beartrap" );
static const efftype_id effect_bite( "bite" );
static const efftype_id effect_bleed( "bleed" );
static const efftype_id effect_blind( "blind" );
static const efftype_id effect_blisters( "blisters" );
static const efftype_id effect_bloodworms( "bloodworms" );
static const efftype_id effect_boomered( "boomered" );
static const efftype_id effect_brainworms( "brainworms" );
static const efftype_id effect_cold( "cold" );
static const efftype_id effect_common_cold( "common_cold" );
static const efftype_id effect_contacts( "contacts" );
static const efftype_id effect_controlled( "controlled" );
static const efftype_id effect_corroding( "corroding" );
static const efftype_id effect_cough_suppress( "cough_suppress" );
static const efftype_id effect_recently_coughed( "recently_coughed" );
static const efftype_id effect_crushed( "crushed" );
static const efftype_id effect_darkness( "darkness" );
static const efftype_id effect_deaf( "deaf" );
static const efftype_id effect_dermatik( "dermatik" );
static const efftype_id effect_disinfected( "disinfected" );
static const efftype_id effect_downed( "downed" );
static const efftype_id effect_drunk( "drunk" );
static const efftype_id effect_earphones( "earphones" );
static const efftype_id effect_flu( "flu" );
static const efftype_id effect_foodpoison( "foodpoison" );
static const efftype_id effect_frostbite( "frostbite" );
static const efftype_id effect_frostbite_recovery( "frostbite_recovery" );
static const efftype_id effect_fungus( "fungus" );
static const efftype_id effect_glowing( "glowing" );
static const efftype_id effect_glowy_led( "glowy_led" );
static const efftype_id effect_got_checked( "got_checked" );
static const efftype_id effect_grabbed( "grabbed" );
static const efftype_id effect_grabbing( "grabbing" );
static const efftype_id effect_harnessed( "harnessed" );
static const efftype_id effect_heavysnare( "heavysnare" );
static const efftype_id effect_hot( "hot" );
static const efftype_id effect_hot_speed( "hot_speed" );
static const efftype_id effect_infected( "infected" );
static const efftype_id effect_in_pit( "in_pit" );
static const efftype_id effect_jetinjector( "jetinjector" );
static const efftype_id effect_lack_sleep( "lack_sleep" );
static const efftype_id effect_lightsnare( "lightsnare" );
static const efftype_id effect_lying_down( "lying_down" );
static const efftype_id effect_magnesium_supplements( "magnesium" );
static const efftype_id effect_masked_scent( "masked_scent" );
static const efftype_id effect_mending( "mending" );
static const efftype_id effect_meth( "meth" );
static const efftype_id effect_narcosis( "narcosis" );
static const efftype_id effect_nausea( "nausea" );
static const efftype_id effect_no_sight( "no_sight" );
static const efftype_id effect_onfire( "onfire" );
static const efftype_id effect_paincysts( "paincysts" );
static const efftype_id effect_pet( "pet" );
static const efftype_id effect_pkill1( "pkill1" );
static const efftype_id effect_pkill2( "pkill2" );
static const efftype_id effect_pkill3( "pkill3" );
static const efftype_id effect_recover( "recover" );
static const efftype_id effect_ridden( "ridden" );
static const efftype_id effect_riding( "riding" );
static const efftype_id effect_sleep( "sleep" );
static const efftype_id effect_slept_through_alarm( "slept_through_alarm" );
static const efftype_id effect_stunned( "stunned" );
static const efftype_id effect_tapeworm( "tapeworm" );
static const efftype_id effect_tied( "tied" );
static const efftype_id effect_took_prozac( "took_prozac" );
static const efftype_id effect_took_xanax( "took_xanax" );
static const efftype_id effect_under_op( "under_operation" );
static const efftype_id effect_webbed( "webbed" );
static const efftype_id effect_weed_high( "weed_high" );
static const efftype_id effect_winded( "winded" );

static const trait_id trait_ACIDBLOOD( "ACIDBLOOD" );
static const trait_id trait_ACIDPROOF( "ACIDPROOF" );
static const trait_id trait_ADRENALINE( "ADRENALINE" );
static const trait_id trait_ANTENNAE( "ANTENNAE" );
static const trait_id trait_ANTLERS( "ANTLERS" );
static const trait_id trait_BADBACK( "BADBACK" );
static const trait_id trait_BARK( "BARK" );
static const trait_id trait_BIRD_EYE( "BIRD_EYE" );
static const trait_id trait_CANNIBAL( "CANNIBAL" );
static const trait_id trait_CENOBITE( "CENOBITE" );
static const trait_id trait_CEPH_EYES( "CEPH_EYES" );
static const trait_id trait_CEPH_VISION( "CEPH_VISION" );
static const trait_id trait_CF_HAIR( "CF_HAIR" );
static const trait_id trait_CHITIN_FUR( "CHITIN_FUR" );
static const trait_id trait_CHITIN_FUR2( "CHITIN_FUR2" );
static const trait_id trait_CHITIN_FUR3( "CHITIN_FUR3" );
static const trait_id trait_CHLOROMORPH( "CHLOROMORPH" );
static const trait_id trait_CLUMSY( "CLUMSY" );
static const trait_id trait_COLDBLOOD4( "COLDBLOOD4" );
static const trait_id trait_DEAF( "DEAF" );
static const trait_id trait_DEBUG_BIONIC_POWER( "DEBUG_BIONIC_POWER" );
static const trait_id trait_DEBUG_CLOAK( "DEBUG_CLOAK" );
static const trait_id trait_DEBUG_NIGHTVISION( "DEBUG_NIGHTVISION" );
static const trait_id trait_DEBUG_NODMG( "DEBUG_NODMG" );
static const trait_id trait_DEBUG_NOTEMP( "DEBUG_NOTEMP" );
static const trait_id trait_DEBUG_HS( "DEBUG_HS" );
static const trait_id trait_DEBUG_LS( "DEBUG_LS" );
static const trait_id trait_DEFT( "DEFT" );
static const trait_id trait_DISORGANIZED( "DISORGANIZED" );
static const trait_id trait_DISRESISTANT( "DISRESISTANT" );
static const trait_id trait_DOWN( "DOWN" );
static const trait_id trait_EASYSLEEPER( "EASYSLEEPER" );
static const trait_id trait_EASYSLEEPER2( "EASYSLEEPER2" );
static const trait_id trait_EATHEALTH( "EATHEALTH" );
static const trait_id trait_ELECTRORECEPTORS( "ELECTRORECEPTORS" );
static const trait_id trait_ELFA_FNV( "ELFA_FNV" );
static const trait_id trait_ELFA_NV( "ELFA_NV" );
static const trait_id trait_FASTLEARNER( "FASTLEARNER" );
static const trait_id trait_FAT( "FAT" );
static const trait_id trait_FEL_NV( "FEL_NV" );
static const trait_id trait_FELINE_FUR( "FELINE_FUR" );
static const trait_id trait_FUR( "FUR" );
static const trait_id trait_GILLS( "GILLS" );
static const trait_id trait_GILLS_CEPH( "GILLS_CEPH" );
static const trait_id trait_GLASSJAW( "GLASSJAW" );
static const trait_id trait_HATES_BOOKS( "HATES_BOOKS" );
static const trait_id trait_HEAVYSLEEPER( "HEAVYSLEEPER" );
static const trait_id trait_HEAVYSLEEPER2( "HEAVYSLEEPER2" );
static const trait_id trait_HOOVES( "HOOVES" );
static const trait_id trait_HORNS_POINTED( "HORNS_POINTED" );
static const trait_id trait_HOARDER( "HOARDER" );
static const trait_id trait_HOLLOW_BONES( "HOLLOW_BONES" );
static const trait_id trait_HUGE( "HUGE" );
static const trait_id trait_HUGE_OK( "HUGE_OK" );
static const trait_id trait_ILLITERATE( "ILLITERATE" );
static const trait_id trait_INFIMMUNE( "INFIMMUNE" );
static const trait_id trait_INSOMNIA( "INSOMNIA" );
static const trait_id trait_INT_SLIME( "INT_SLIME" );
static const trait_id trait_LARGE( "LARGE" );
static const trait_id trait_LARGE_OK( "LARGE_OK" );
static const trait_id trait_LEG_TENTACLES( "LEG_TENTACLES" );
static const trait_id trait_LEG_TENT_BRACE( "LEG_TENT_BRACE" );
static const trait_id trait_LIGHT_BONES( "LIGHT_BONES" );
static const trait_id trait_LIGHTFUR( "LIGHTFUR" );
static const trait_id trait_LIGHTSTEP( "LIGHTSTEP" );
static const trait_id trait_LOVES_BOOKS( "LOVES_BOOKS" );
static const trait_id trait_LUPINE_FUR( "LUPINE_FUR" );
static const trait_id trait_MEMBRANE( "MEMBRANE" );
static const trait_id trait_MOREPAIN( "MORE_PAIN" );
static const trait_id trait_MOREPAIN2( "MORE_PAIN2" );
static const trait_id trait_MOREPAIN3( "MORE_PAIN3" );
static const trait_id trait_MYOPIC( "MYOPIC" );
static const trait_id trait_M_DEPENDENT( "M_DEPENDENT" );
static const trait_id trait_M_IMMUNE( "M_IMMUNE" );
static const trait_id trait_M_SKIN2( "M_SKIN2" );
static const trait_id trait_M_SKIN3( "M_SKIN3" );
static const trait_id trait_NAUSEA( "NAUSEA" );
static const trait_id trait_NIGHTVISION( "NIGHTVISION" );
static const trait_id trait_NIGHTVISION2( "NIGHTVISION2" );
static const trait_id trait_NIGHTVISION3( "NIGHTVISION3" );
static const trait_id trait_NOMAD( "NOMAD" );
static const trait_id trait_NOMAD2( "NOMAD2" );
static const trait_id trait_NOMAD3( "NOMAD3" );
static const trait_id trait_NOPAIN( "NOPAIN" );
static const trait_id trait_NO_THIRST( "NO_THIRST" );
static const trait_id trait_PACIFIST( "PACIFIST" );
static const trait_id trait_PACKMULE( "PACKMULE" );
static const trait_id trait_PADDED_FEET( "PADDED_FEET" );
static const trait_id trait_PAINRESIST( "PAINRESIST" );
static const trait_id trait_PAINRESIST_TROGLO( "PAINRESIST_TROGLO" );
static const trait_id trait_PARAIMMUNE( "PARAIMMUNE" );
static const trait_id trait_PARKOUR( "PARKOUR" );
static const trait_id trait_PAWS( "PAWS" );
static const trait_id trait_PAWS_LARGE( "PAWS_LARGE" );
static const trait_id trait_PER_SLIME( "PER_SLIME" );
static const trait_id trait_PER_SLIME_OK( "PER_SLIME_OK" );
static const trait_id trait_PROF_FOODP( "PROF_FOODP" );
static const trait_id trait_PROF_SKATER( "PROF_SKATER" );
static const trait_id trait_PSYCHOPATH( "PSYCHOPATH" );
static const trait_id trait_PYROMANIA( "PYROMANIA" );
static const trait_id trait_QUILLS( "QUILLS" );
static const trait_id trait_RADIOGENIC( "RADIOGENIC" );
static const trait_id trait_ROOTS2( "ROOTS2" );
static const trait_id trait_ROOTS3( "ROOTS3" );
static const trait_id trait_SAPIOVORE( "SAPIOVORE" );
static const trait_id trait_SAVANT( "SAVANT" );
static const trait_id trait_SEESLEEP( "SEESLEEP" );
static const trait_id trait_SELFAWARE( "SELFAWARE" );
static const trait_id trait_SHELL( "SHELL" );
static const trait_id trait_SHELL2( "SHELL2" );
static const trait_id trait_SHOUT2( "SHOUT2" );
static const trait_id trait_SHOUT3( "SHOUT3" );
static const trait_id trait_SLIMESPAWNER( "SLIMESPAWNER" );
static const trait_id trait_SLIMY( "SLIMY" );
static const trait_id trait_SLOWLEARNER( "SLOWLEARNER" );
static const trait_id trait_SPINES( "SPINES" );
static const trait_id trait_SPIRITUAL( "SPIRITUAL" );
static const trait_id trait_SQUEAMISH( "SQUEAMISH" );
static const trait_id trait_STOCKY_TROGLO( "STOCKY_TROGLO" );
static const trait_id trait_STRONGSTOMACH( "STRONGSTOMACH" );
static const trait_id trait_SUNLIGHT_DEPENDENT( "SUNLIGHT_DEPENDENT" );
static const trait_id trait_THORNS( "THORNS" );
static const trait_id trait_THRESH_SPIDER( "THRESH_SPIDER" );
static const trait_id trait_TOUGH_FEET( "TOUGH_FEET" );
static const trait_id trait_THRESH_CEPHALOPOD( "THRESH_CEPHALOPOD" );
static const trait_id trait_THRESH_INSECT( "THRESH_INSECT" );
static const trait_id trait_THRESH_PLANT( "THRESH_PLANT" );
static const trait_id trait_TRANSPIRATION( "TRANSPIRATION" );
static const trait_id trait_URSINE_EYE( "URSINE_EYE" );
static const trait_id trait_URSINE_FUR( "URSINE_FUR" );
static const trait_id trait_VISCOUS( "VISCOUS" );
static const trait_id trait_VOMITOUS( "VOMITOUS" );
static const trait_id trait_WATERSLEEP( "WATERSLEEP" );
static const trait_id trait_WEAKSTOMACH( "WEAKSTOMACH" );
static const trait_id trait_WEBBED( "WEBBED" );
static const trait_id trait_WEB_SPINNER( "WEB_SPINNER" );
static const trait_id trait_WEB_WALKER( "WEB_WALKER" );
static const trait_id trait_WEB_WEAVER( "WEB_WEAVER" );
static const trait_id trait_WOOLALLERGY( "WOOLALLERGY" );

static const trait_id debug_nodmg( "DEBUG_NODMG" );

static const std::string trait_flag_CANNIBAL("CANNIBAL");
static const std::string trait_flag_PSYCHOPATH("PSYCHOPATH");
static const std::string trait_flag_SAPIOVORE("SAPIOVORE");

static const species_id HUMAN( "HUMAN" );
static const species_id ROBOT( "ROBOT" );
static const species_id ZOMBIE( "ZOMBIE" );


static const mtype_id mon_player_blob( "mon_player_blob" );
static const mtype_id mon_shadow_snake( "mon_shadow_snake" );

static const skill_id skill_computer( "computer" );
static const skill_id skill_dodge( "dodge" );
static const skill_id skill_electronics( "electronics" );
static const skill_id skill_firstaid( "firstaid" );
static const skill_id skill_throw( "throw" );
static const skill_id skill_gun( "gun" );
static const skill_id skill_swimming( "swimming" );
static const skill_id skill_survival( "survival" );

static const std::string flag_AUTODOC( "AUTODOC" );
static const std::string flag_AUTODOC_COUCH( "AUTODOC_COUCH" );
static const std::string flag_BUTCHER_EQ( "BUTCHER_EQ" );
static const std::string flag_EATEN_COLD("EATEN_COLD");
static const std::string flag_FISH_GOOD("FISH_GOOD");
static const std::string flag_FISH_POOR("FISH_POOR");
static const std::string flag_FLAT_SURF("FLAT_SURF");
static const std::string flag_FORAGE_HALLU("FORAGE_HALLU");

static const std::string flag_FORAGE_POISON("FORAGE_POISON");
static const std::string flag_HIDDEN_HALLU("HIDDEN_HALLU");

static const std::string flag_HIDDEN_POISON("HIDDEN_POISON");
static const std::string flag_GIBBED("GIBBED");
static const std::string flag_KITCHEN("KITCHEN");
static const std::string flag_MAG_DESTROY("MAG_DESTROY");
static const std::string flag_MESSY("MESSY");
static const std::string flag_SAFECRACK("SAFECRACK");
static const std::string flag_SUPPORTS_ROOF("SUPPORTS_ROOF");
static const std::string flag_FIELD_DRESS_FAILED("FIELD_DRESS_FAILED");
static const std::string flag_FIELD_DRESS("FIELD_DRESS");
static const std::string flag_REQUIRES_TINDER("REQUIRES_TINDER");
static const std::string flag_PULPED("PULPED");
static const std::string flag_QUARTERED("QUARTERED");
static const std::string flag_RELOAD_ONE("RELOAD_ONE");
static const std::string flag_SKINNED("SKINNED");
static const std::string flag_SPEEDLOADER("SPEEDLOADER");
static const std::string flag_TREE("TREE");


static const quality_id qual_CUT_FINE("CUT_FINE");
static const quality_id qual_BUTCHER("BUTCHER");
static const quality_id qual_SAW_W("SAW_W");
static const quality_id qual_SAW_M("SAW_M");


static const zone_type_id zone_type_FARM_PLOT("FARM_PLOT");

#endif // STRING_CONSTS_H
