FIND_PACKAGE(Git)

EXECUTE_PROCESS(
	COMMAND ${GIT_EXECUTABLE} describe --tags --always --dirty --match "[0-9]*.[0-9]*"
	WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
	OUTPUT_VARIABLE VERSION
	OUTPUT_STRIP_TRAILING_WHITESPACE
)
CONFIGURE_FILE(${SRC} ${DST} @ONLY)
