name: "Issue Labeler"

on:
  issues:
    types:
      - opened

jobs:
  uses:
    name: triage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fuxingloh/multi-labeler@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: '.github/issue-labels.yml'
