name: "Pull Request Labeler"
on:
  # Permissions are manually scoped down so safe to use pull_request_target.
  - pull_request_target

# Copied from https://github.com/fuxingloh/multi-labeler/blob/480c3b47408260ebbd086108d9fe79db99a3310e/README.md?plain=1#L58-L64
permissions:
  contents: read # the config file
  pull-requests: write # for labeling pull requests (on: pull_request_target or on: pull_request)

jobs:
  triage:
    permissions:
      contents: read  # for actions/labeler to determine modified files
      pull-requests: write  # for actions/labeler to add labels to PRs
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@bcd50af464202999e57f556b4aefcf05a34abf85 # v5.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
