name: Auto request review


on:
  pull_request_target:
    types: [opened, synchronize, ready_for_review, reopened]


concurrency:
  group: request-review-${{ github.event.pull_request.number }}
  cancel-in-progress: true


jobs:
  auto-request-review:
    # Do not spam reviewer with PRs in forks. If fork owners wish to alert
    # people of their changes they may change this line themselves.
    if: github.repository == 'CleverRaven/Cataclysm-DDA'
    name: Auto request review
    runs-on: ubuntu-latest
    steps:
      - name: Request review
        uses: qrox/auto-request-review@3d551ae9363f17fcc74973b2c93cefa64e9b584c
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/reviewers.yml
