name: Auto request review


on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]


jobs:
  auto-request-review:
    # Do not spam reviewer with PRs in forks. If fork owners wish to alert
    # people of their changes they may change this line themselves.
    if: github.repository == 'CleverRaven/Cataclysm-DDA'
    name: Auto request review
    runs-on: ubuntu-latest
    steps:
      - name: Request review
        uses: necojackarc/auto-request-review@v0.11.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/reviewers.yml
