on:
  push:
    branches:
      - master
name: "Push translation template"
jobs:
  push-template:
    runs-on: ubuntu-20.04
    steps:
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install gettext python3-pip
          sudo pip3 install transifex-client
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Generate translation template"
        run: |
          lang/update_pot.sh
      - name: "Push translation template"
        env:
          TOKEN: ${{ secrets.TX_TOKEN }}
        run: |
          export TX_TOKEN=$TOKEN
          tx push --source --no-interactive --resource cataclysm-dda.master-cataclysm-dda
          unset TX_TOKEN
          unset TOKEN
